/**************************************************************************************************\ 
 *** 
 *** System               : System
 *** ECU                  : EcuInstance
 *** Configuration        : EcuConfiguration_EcuInstance1
 *** Codefile             : MemMap.h
 ***
 *** Generated by SystemDesk
 *** Generation date: 2025-06-11 08:50:24
 ***
 *** SystemDesk version   : 5.6.0.13023
 *** Copyright (c) 2015 dSPACE GmbH
\**************************************************************************************************/ 


