/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcucValueCollection
 *** Codefile            : Rte_TargetSpeedControl.h
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2025-06-11 10:13:55
 ***
 *** SystemDesk version  : 5.6.0.13023
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/

#ifndef RTE_TARGETSPEEDCONTROL_H
#define RTE_TARGETSPEEDCONTROL_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
#include "Rte_TargetSpeedControl_Type.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_TARGETSPEEDCONTROL_C

/* Init value(s). */
#define Rte_InitValue_TargetSpeedButtonState_Value 0 
#define Rte_InitValue_TargetSpeed_Value 0.F 
#endif 
#endif 
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_TARGETSPEEDCONTROL_C

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_SpeedControl_TargetSpeedButtonState_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      uint8
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_SpeedControl_TargetSpeedButtonState_Value() \
(\
   Rte_Signal_12\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWrite_SpeedControl_TargetSpeed_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an "implicit" write on a sender-receiver communication data with "data" semantics
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      float32            Value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWrite_SpeedControl_TargetSpeed_Value(Value) \
(\
   Rte_Signal_6 = (Value)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWriteRef_SpeedControl_TargetSpeed_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit write on a sender-receiver communication data item with data semantic
 s.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      float32 *
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWriteRef_SpeedControl_TargetSpeed_Value() \
(\
   ((float32 *) &Rte_Signal_6)\
)

#endif 
#endif 
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/


/* runnables */
#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */ 

extern void TargetSpeedControl_SpeedControl(void);
#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 


#endif/*RTE_TARGETSPEEDCONTROL_H */
/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
