/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcuConfiguration_EcuInstance1
 *** Codefile            : EcuM_Types.h
 ***
 *** Generated by SystemDesk 5.6.0.13023
 ***
 *** Copyright (c) 2018 dSPACE GmbH
\**************************************************************************************************/

#ifndef ECUM_TYPES_H
#define ECUM_TYPES_H

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/
#include "Std_Types.h"
#include "Os.h"
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
#ifndef ECUM_WKACT_RUN
#define ECUM_WKACT_RUN 0x00U 
#endif  /* ECUM_WKACT_RUN */

#ifndef ECUM_WKACT_TTII
#define ECUM_WKACT_TTII 0x02U 
#endif  /* ECUM_WKACT_TTII */

#ifndef ECUM_WKACT_SHUTDOWN
#define ECUM_WKACT_SHUTDOWN 0x03U 
#endif  /* ECUM_WKACT_SHUTDOWN */

#ifndef ECUM_WKSTATUS_NONE
#define ECUM_WKSTATUS_NONE 0U 
#endif  /* ECUM_WKSTATUS_NONE */

#ifndef ECUM_WKSTATUS_PENDING
#define ECUM_WKSTATUS_PENDING 1U 
#endif  /* ECUM_WKSTATUS_PENDING */

#ifndef ECUM_WKSTATUS_VALIDATED
#define ECUM_WKSTATUS_VALIDATED 2U 
#endif  /* ECUM_WKSTATUS_VALIDATED */

#ifndef ECUM_WKSTATUS_EXPIRED
#define ECUM_WKSTATUS_EXPIRED 3U 
#endif  /* ECUM_WKSTATUS_EXPIRED */

#ifndef ECUM_BOOT_TARGET_APP
#define ECUM_BOOT_TARGET_APP 0U 
#endif  /* ECUM_BOOT_TARGET_APP */

#ifndef ECUM_BOOT_TARGET_OEM_BOOTLOADER
#define ECUM_BOOT_TARGET_OEM_BOOTLOADER 1U 
#endif  /* ECUM_BOOT_TARGET_OEM_BOOTLOADER */

#ifndef ECUM_BOOT_TARGET_SYS_BOOTLOADER
#define ECUM_BOOT_TARGET_SYS_BOOTLOADER 2U 
#endif  /* ECUM_BOOT_TARGET_SYS_BOOTLOADER */

#ifndef ECUM_SUBSTATE_MASK
#define ECUM_SUBSTATE_MASK 0x0fU 
#endif  /* ECUM_SUBSTATE_MASK */

#ifndef ECUM_STATE_STARTUP
#define ECUM_STATE_STARTUP 0x10U 
#endif  /* ECUM_STATE_STARTUP */

#ifndef ECUM_STATE_STARTUP_ONE
#define ECUM_STATE_STARTUP_ONE 0x11U 
#endif  /* ECUM_STATE_STARTUP_ONE */

#ifndef ECUM_STATE_STARTUP_TWO
#define ECUM_STATE_STARTUP_TWO 0x12U 
#endif  /* ECUM_STATE_STARTUP_TWO */

#ifndef ECUM_STATE_WAKEUP
#define ECUM_STATE_WAKEUP 0x20U 
#endif  /* ECUM_STATE_WAKEUP */

#ifndef ECUM_STATE_WAKEUP_ONE
#define ECUM_STATE_WAKEUP_ONE 0x21U 
#endif  /* ECUM_STATE_WAKEUP_ONE */

#ifndef ECUM_STATE_WAKEUP_VALIDATION
#define ECUM_STATE_WAKEUP_VALIDATION 0x22U 
#endif  /* ECUM_STATE_WAKEUP_VALIDATION */

#ifndef ECUM_STATE_WAKEUP_REACTION
#define ECUM_STATE_WAKEUP_REACTION 0x23U 
#endif  /* ECUM_STATE_WAKEUP_REACTION */

#ifndef ECUM_STATE_WAKEUP_TWO
#define ECUM_STATE_WAKEUP_TWO 0x24U 
#endif  /* ECUM_STATE_WAKEUP_TWO */

#ifndef ECUM_STATE_WAKEUP_WAKESLEEP
#define ECUM_STATE_WAKEUP_WAKESLEEP 0x25U 
#endif  /* ECUM_STATE_WAKEUP_WAKESLEEP */

#ifndef ECUM_STATE_WAKEUP_TTII
#define ECUM_STATE_WAKEUP_TTII 0x26U 
#endif  /* ECUM_STATE_WAKEUP_TTII */

#ifndef ECUM_STATE_RUN
#define ECUM_STATE_RUN 0x30U 
#endif  /* ECUM_STATE_RUN */

#ifndef ECUM_STATE_APP_RUN
#define ECUM_STATE_APP_RUN 0x32U 
#endif  /* ECUM_STATE_APP_RUN */

#ifndef ECUM_STATE_APP_POST_RUN
#define ECUM_STATE_APP_POST_RUN 0x33U 
#endif  /* ECUM_STATE_APP_POST_RUN */

#ifndef ECUM_STATE_SHUTDOWN
#define ECUM_STATE_SHUTDOWN 0x40U 
#endif  /* ECUM_STATE_SHUTDOWN */

#ifndef ECUM_STATE_PREP_SHUTDOWN
#define ECUM_STATE_PREP_SHUTDOWN 0x44U 
#endif  /* ECUM_STATE_PREP_SHUTDOWN */

#ifndef ECUM_STATE_GO_SLEEP
#define ECUM_STATE_GO_SLEEP 0x49U 
#endif  /* ECUM_STATE_GO_SLEEP */

#ifndef ECUM_STATE_GO_OFF_ONE
#define ECUM_STATE_GO_OFF_ONE 0x4dU 
#endif  /* ECUM_STATE_GO_OFF_ONE */

#ifndef ECUM_STATE_GO_OFF_TWO
#define ECUM_STATE_GO_OFF_TWO 0x4eU 
#endif  /* ECUM_STATE_GO_OFF_TWO */

#ifndef ECUM_STATE_SLEEP
#define ECUM_STATE_SLEEP 0x50U 
#endif  /* ECUM_STATE_SLEEP */

#ifndef ECUM_STATE_RESET
#define ECUM_STATE_RESET 0x90U 
#endif  /* ECUM_STATE_RESET */

#ifndef ECUM_STATE_OFF
#define ECUM_STATE_OFF 0x80U 
#endif  /* ECUM_STATE_OFF */

#ifndef ECUM_INCLUDE_BSWM
#define ECUM_INCLUDE_BSWM STD_OFF 
#endif  /* ECUM_INCLUDE_BSWM */

#ifndef ECUM_INCLUDE_CANTRCV
#define ECUM_INCLUDE_CANTRCV STD_OFF 
#endif  /* ECUM_INCLUDE_CANTRCV */

#ifndef ECUM_INCLUDE_CANIF
#define ECUM_INCLUDE_CANIF STD_OFF 
#endif  /* ECUM_INCLUDE_CANIF */

#ifndef ECUM_INCLUDE_DEM
#define ECUM_INCLUDE_DEM STD_OFF 
#endif  /* ECUM_INCLUDE_DEM */

#ifndef ECUM_INCLUDE_FRTRCV
#define ECUM_INCLUDE_FRTRCV STD_OFF 
#endif  /* ECUM_INCLUDE_FRTRCV */

#ifndef ECUM_INCLUDE_GPT
#define ECUM_INCLUDE_GPT STD_OFF 
#endif  /* ECUM_INCLUDE_GPT */

#ifndef ECUM_INCLUDE_ICU
#define ECUM_INCLUDE_ICU STD_OFF 
#endif  /* ECUM_INCLUDE_ICU */

#ifndef ECUM_INCLUDE_LINTRCV
#define ECUM_INCLUDE_LINTRCV STD_OFF 
#endif  /* ECUM_INCLUDE_LINTRCV */

#ifndef ECUM_INCLUDE_MCU
#define ECUM_INCLUDE_MCU STD_OFF 
#endif  /* ECUM_INCLUDE_MCU */

#ifndef ECUM_INCLUDE_NVM
#define ECUM_INCLUDE_NVM STD_OFF 
#endif  /* ECUM_INCLUDE_NVM */

#ifndef ECUM_WAKEUP_SUPPORT
#define ECUM_WAKEUP_SUPPORT STD_ON 
#endif  /* ECUM_WAKEUP_SUPPORT */

#ifndef ECUM_GPT_WAKEUP_API_AVAILABLE
#define ECUM_GPT_WAKEUP_API_AVAILABLE STD_OFF 
#endif  /* ECUM_GPT_WAKEUP_API_AVAILABLE */

#ifndef ECUM_ICU_CHECK_WAKEUP_API_AVAILABLE
#define ECUM_ICU_CHECK_WAKEUP_API_AVAILABLE STD_OFF 
#endif  /* ECUM_ICU_CHECK_WAKEUP_API_AVAILABLE */

#ifndef ECUM_ICU_ENABLE_WAKEUP_API_AVAILABLE
#define ECUM_ICU_ENABLE_WAKEUP_API_AVAILABLE STD_OFF 
#endif  /* ECUM_ICU_ENABLE_WAKEUP_API_AVAILABLE */

#ifndef ECUM_ICU_DISABLE_WAKEUP_API_AVAILABLE
#define ECUM_ICU_DISABLE_WAKEUP_API_AVAILABLE STD_OFF 
#endif  /* ECUM_ICU_DISABLE_WAKEUP_API_AVAILABLE */

#ifndef ECUM_INCLUDE_COMM
#define ECUM_INCLUDE_COMM STD_OFF 
#endif  /* ECUM_INCLUDE_COMM */

#ifndef ECUM_TTII_ENABLED
#define ECUM_TTII_ENABLED FALSE 
#endif  /* ECUM_TTII_ENABLED */

#ifndef ECUM_CURRENT_MODE_PORT_AVAILABLE
#define ECUM_CURRENT_MODE_PORT_AVAILABLE STD_OFF 
#endif  /* ECUM_CURRENT_MODE_PORT_AVAILABLE */

#ifndef ECUM_CANIF_WAKEUP_SUPPORT
#define ECUM_CANIF_WAKEUP_SUPPORT STD_OFF 
#endif  /* ECUM_CANIF_WAKEUP_SUPPORT */

#ifndef ECUM_CANIF_WAKEUP_VALIDATION_SUPPORT
#define ECUM_CANIF_WAKEUP_VALIDATION_SUPPORT STD_OFF 
#endif  /* ECUM_CANIF_WAKEUP_VALIDATION_SUPPORT */

#ifndef ECUM_LINIF_WAKEUP_SUPPORT
#define ECUM_LINIF_WAKEUP_SUPPORT STD_OFF 
#endif  /* ECUM_LINIF_WAKEUP_SUPPORT */

#ifndef ECUM_INIT_PARAM_VOID
#define ECUM_INIT_PARAM_VOID 0 
#endif  /* ECUM_INIT_PARAM_VOID */

#ifndef ECUM_INIT_PARAM_NULL
#define ECUM_INIT_PARAM_NULL 1 
#endif  /* ECUM_INIT_PARAM_NULL */

#ifndef ECUM_INIT_PARAM_PTR
#define ECUM_INIT_PARAM_PTR 2 
#endif  /* ECUM_INIT_PARAM_PTR */

#ifndef ECUM_WKSTATUS_ENABLED
#define ECUM_WKSTATUS_ENABLED 6 
#endif  /* ECUM_WKSTATUS_ENABLED */

#ifndef ECUM_WKSOURCE_POWER
#define ECUM_WKSOURCE_POWER 0x0001 
#endif  /* ECUM_WKSOURCE_POWER */

#ifndef ECUM_WKSOURCE_RESET
#define ECUM_WKSOURCE_RESET 0x0002 
#endif  /* ECUM_WKSOURCE_RESET */

#ifndef ECUM_WKSOURCE_INTERNAL_RESET
#define ECUM_WKSOURCE_INTERNAL_RESET 0x0004 
#endif  /* ECUM_WKSOURCE_INTERNAL_RESET */

#ifndef ECUM_WKSOURCE_INTERNAL_WDG
#define ECUM_WKSOURCE_INTERNAL_WDG 0x0008 
#endif  /* ECUM_WKSOURCE_INTERNAL_WDG */

#ifndef ECUM_WKSOURCE_EXTERNAL_WDG
#define ECUM_WKSOURCE_EXTERNAL_WDG 0x0010 
#endif  /* ECUM_WKSOURCE_EXTERNAL_WDG */

#ifndef NULL
#define NULL ((void *)0) 
#endif  /* NULL */

#ifndef ECUM_MAIN_FUNCTION_PERIOD
#define ECUM_MAIN_FUNCTION_PERIOD 0.001 
#endif  /* ECUM_MAIN_FUNCTION_PERIOD */

#ifndef ECUM_RUN_MINIMUM_DURATION
#define ECUM_RUN_MINIMUM_DURATION 0 
#endif  /* ECUM_RUN_MINIMUM_DURATION */

#ifndef ECUM_WKSOURCE_TYPE_UNKNOWN
#define ECUM_WKSOURCE_TYPE_UNKNOWN 0 
#endif  /* ECUM_WKSOURCE_TYPE_UNKNOWN */

#ifndef ECUM_WKSOURCE_TYPE_GPT
#define ECUM_WKSOURCE_TYPE_GPT 1 
#endif  /* ECUM_WKSOURCE_TYPE_GPT */

#ifndef ECUM_WKSOURCE_TYPE_CAN
#define ECUM_WKSOURCE_TYPE_CAN 2 
#endif  /* ECUM_WKSOURCE_TYPE_CAN */

#ifndef ECUM_WKSOURCE_TYPE_CANTRCV
#define ECUM_WKSOURCE_TYPE_CANTRCV 3 
#endif  /* ECUM_WKSOURCE_TYPE_CANTRCV */

#ifndef ECUM_WKSOURCE_TYPE_LIN
#define ECUM_WKSOURCE_TYPE_LIN 4 
#endif  /* ECUM_WKSOURCE_TYPE_LIN */

#ifndef ECUM_WKSOURCE_TYPE_LINTRCV
#define ECUM_WKSOURCE_TYPE_LINTRCV 5 
#endif  /* ECUM_WKSOURCE_TYPE_LINTRCV */

#ifndef ECUM_WKSOURCE_TYPE_ICU
#define ECUM_WKSOURCE_TYPE_ICU 6 
#endif  /* ECUM_WKSOURCE_TYPE_ICU */

#ifndef ECUM_WKSOURCE_TYPE_ETHTRCV
#define ECUM_WKSOURCE_TYPE_ETHTRCV 7 
#endif  /* ECUM_WKSOURCE_TYPE_ETHTRCV */

#ifndef ECUM_WKSOURCE_TYPE_FRTRCV
#define ECUM_WKSOURCE_TYPE_FRTRCV 8 
#endif  /* ECUM_WKSOURCE_TYPE_FRTRCV */

#ifndef ECUM_WKSOURCE_TYPE_CDD
#define ECUM_WKSOURCE_TYPE_CDD 9 
#endif  /* ECUM_WKSOURCE_TYPE_CDD */


#define ECUM_TICKS(valueInSeconds) (EcuM_TimeoutType)((valueInSeconds) / ECUM_MAIN_FUNCTION_PERIOD)

#if (ECUM_INCLUDE_MCU == STD_ON)
#include "Mcu_Types.h"
#endif

#if (ECUM_INCLUDE_GPT == STD_ON)
#include "Gpt_Types.h"
#endif

#if (ECUM_INCLUDE_ICU == STD_ON)
#include "Icu_Types.h"
#endif

#if (ECUM_INCLUDE_FRTRCV == STD_ON)
#include "Fr_Types.h"
#include "Fr_GeneralTypes.h"
#endif

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/

#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */ 

/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
typedef void (*EcuM_InitFunctionPtrVoid)(void);
typedef void (*EcuM_InitFunctionPtrParam)(const void*);


typedef uint32 EcuM_WakeupSourceType;
typedef uint8 EcuM_WakeupReactionType;
typedef uint8 EcuM_WakeupStatusType;
typedef uint8 EcuM_BootTargetType;
typedef uint8 EcuM_SleepModeType;
typedef uint8 EcuM_StateType;
typedef uint8 EcuM_UserType;
typedef uint8 EcuM_AppModeType;
typedef uint16 EcuM_TimeoutType;


typedef struct {
	EcuM_WakeupSourceType WakeupSourceMask;
	uint8 McuMode;
	boolean McuSuspended;
} EcuM_SleepModeConfig;

typedef struct {
	uint8 ConfigType;
	uint8 Index;
} EcuM_CommonWakeupSourceConfig;

typedef struct {
	EcuM_TimeoutType CheckWakeupTimeout;
	EcuM_TimeoutType ValidationTimeout;
	boolean RequiresPolling;
	uint8 ComMChannel;
	uint8 NumConfigs;
	EcuM_CommonWakeupSourceConfig* Configs;
} EcuM_WakeupSourceConfig;

typedef struct {
	EcuM_InitFunctionPtrVoid InitFuncVoid;
	EcuM_InitFunctionPtrParam InitFuncParam;
	const void* InitParam;
	uint8 ParamType;
} EcuM_InitListEntryType;

typedef struct {
	EcuM_InitListEntryType* Entries;
	uint8 NumEntries;
} EcuM_InitListType;

typedef struct {
	uint8* CommunicationAllowedEntries;
	uint8 NumEntries;
} EcuM_ComMType;

typedef struct {
	EcuM_InitListType DriverInitListOne;
	EcuM_InitListType DriverInitListTwo;
	EcuM_InitListType DriverInitListThree;
	EcuM_InitListType RestartList;
	AppModeType DefaultAppMode;
	EcuM_TimeoutType RunMinimumDuration;
	EcuM_ComMType ComMData;
	EcuM_SleepModeConfig* SleepModes;
	EcuM_WakeupSourceConfig* WakeupSources;
	void* GptWakeupSources;
	void* IcuWakeupSources;
	void* CanWakeupSources;
	void* FrWakeupSources;
	uint8 DefaultSleepMode;
	uint8 NumSleepModes;
	uint8 NumWakeupSources;
	uint8 NormalMcuMode;
	EcuM_TimeoutType NvM_ReadAllTimeout;
	EcuM_TimeoutType NvM_WriteAllTimeout;
	EcuM_WakeupSourceType TTII_WakeupSourceMask;
	uint8 DefaultShutdownTarget;
	uint8 DefaultResetMode;
	boolean TTII_Enabled;
} EcuM_ConfigType;


/*------------------------------------------------------------------------------------------------*\
  VARIABLE DECLARATIONS
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 

#endif /* ECUM_TYPES_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
