/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcuConfiguration_EcuInstance1
 *** Codefile            : EcuM_Callout.c
 ***
 *** Generated by SystemDesk 5.6.0.13023
 *** Generation date: 2025-06-11 08:50:22
 ***
 *** Copyright (c) 2018 dSPACE GmbH
\**************************************************************************************************/

#ifndef ECUM_CALLOUT_C
#define ECUM_CALLOUT_C

/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/
#include "EcuM.h"
#include "EcuM_Callout.h"
#include "EcuM_Internal.h"

/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/

#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */

/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  VARIABLE DECLARATIONS
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_AL_DriverInitOne
 *** 
 *** DESCRIPTION:
 ***     This callout shall provide driver initialization and other hardware-related startup
 ***     activities in case of a power on reset.
 ***     
 ***     ServiceID  : 0x33
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	const EcuM_ConfigType* ConfigPtr Pointer to the EcuM post-build configuration which contains pointers to all other BSW
 ***     module post-build configurations. 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_AL_DriverInitOne_START_SEC_CODE
#include "MemMap.h"
void EcuM_AL_DriverInitOne(const EcuM_ConfigType* ConfigPtr)
{
	/* Begin Code EcuM_AL_DriverInitOne */
    EcuM_InitializeList(&ConfigPtr->DriverInitListOne);
	/* End Code EcuM_AL_DriverInitOne */

}
#define EcuM_AL_DriverInitOne_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_AL_DriverInitThree
 *** 
 *** DESCRIPTION:
 ***     This callout shall provide driver initialization of drivers which need OS and need to
 ***     wait for the NvM_ReadAll job to finish.
 ***     
 ***     ServiceID  : 0x35
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	const EcuM_ConfigType* ConfigPtr Pointer to the EcuM post-build configuration which contains pointers to all other BSW
 ***     module post-build configurations. 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_AL_DriverInitThree_START_SEC_CODE
#include "MemMap.h"
void EcuM_AL_DriverInitThree(const EcuM_ConfigType* ConfigPtr)
{
	/* Begin Code EcuM_AL_DriverInitThree */
    EcuM_InitializeList(&ConfigPtr->DriverInitListThree);
	/* End Code EcuM_AL_DriverInitThree */

}
#define EcuM_AL_DriverInitThree_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_AL_DriverInitTwo
 *** 
 *** DESCRIPTION:
 ***     This callout shall provide driver initialization of drivers which need OS and do not
 ***     need to wait for the NvM_ReadAll job to finish.
 ***     
 ***     ServiceID  : 0x34
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	const EcuM_ConfigType* ConfigPtr Pointer to the EcuM post-build configuration which contains pointers to all other BSW
 ***     module post-build configurations. 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_AL_DriverInitTwo_START_SEC_CODE
#include "MemMap.h"
void EcuM_AL_DriverInitTwo(const EcuM_ConfigType* ConfigPtr)
{
	/* Begin Code EcuM_AL_DriverInitTwo */
    EcuM_InitializeList(&ConfigPtr->DriverInitListTwo);
	/* End Code EcuM_AL_DriverInitTwo */

}
#define EcuM_AL_DriverInitTwo_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_AL_DriverInitZero
 *** 
 *** DESCRIPTION:
 ***     This callout shall provide driver initialization and other hardware-related startup
 ***     activities for loading the post-build configuration data. Beware: Here only
 ***     pre-compile and link-time configurable modules may be used.
 ***     
 ***     ServiceID  : 0x31
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_AL_DriverInitZero_START_SEC_CODE
#include "MemMap.h"
void EcuM_AL_DriverInitZero(void)
{
	/* Begin Code EcuM_AL_DriverInitZero */

    /* init list zero is not post-build configurable */
    EcuM_InitializeList(&EcuM_InitListZero);

	/* End Code EcuM_AL_DriverInitZero */

}
#define EcuM_AL_DriverInitZero_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_AL_DriverRestart
 *** 
 *** DESCRIPTION:
 ***     This callout shall provide driver initialization and other hardware-related startup
 ***     activities in the wakeup case.
 ***     
 ***     ServiceID  : 0x45
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	const EcuM_ConfigType* ConfigPtr Pointer to the EcuM post-build configuration which contains pointers to all other BSW
 ***     module post-build configurations. 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_AL_DriverRestart_START_SEC_CODE
#include "MemMap.h"
void EcuM_AL_DriverRestart(const EcuM_ConfigType* ConfigPtr)
{
	/* Begin Code EcuM_AL_DriverRestart */
    EcuM_InitializeList(&ConfigPtr->RestartList);
	/* End Code EcuM_AL_DriverRestart */

}
#define EcuM_AL_DriverRestart_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_AL_SwitchOff
 *** 
 *** DESCRIPTION:
 ***     This callout shall take the code for shutting off the power supply of the ECU. If the
 ***     ECU cannot unpower itself, a reset may be an adequate reaction.
 ***     
 ***     ServiceID  : 0x3e
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_AL_SwitchOff_START_SEC_CODE
#include "MemMap.h"
void EcuM_AL_SwitchOff(void)
{
	/* Begin Code EcuM_AL_SwitchOff */
    /* Add your own implementation here! */
    /* End Code EcuM_AL_SwitchOff */

}
#define EcuM_AL_SwitchOff_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_CheckRamHash
 *** 
 *** DESCRIPTION:
 ***     This callout is intended to provide a RAM integrity test. The goal of this test is to
 ***     ensure that after a long SLEEP duration, RAM contents is still consistent.
 ***     The check does not need to be exhaustive since this would consume quite some
 ***     processing time during wakeups. A well designed check will execute quickly
 ***     and detect RAM integrity defects with a sufficient probability. This
 ***     specification does not make any assumption about the algorithm chosen for a
 ***     particular ECU. The areas of RAM which will be checked have to be chosen
 ***     carefully. It depends on the check algorithm itself and the task structure.
 ***     Stack contents of the task executing the RAM check e.g. very likely cannot
 ***     be checked. It is good practice to have the hash generation and checking in
 ***     the same task and that this task is not preemptible and that there is only
 ***     little activity between hash generation and hash check. The RAM check itself
 ***     is provided by the system designer. In case of applied multi core and
 ***     existence of Satellite-EcuM(s): this API will be called by the Master-EcuM
 ***     only.
 ***     
 ***     ServiceID  : 0x43
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    uint8
\**************************************************************************************************/
#define EcuM_CheckRamHash_START_SEC_CODE
#include "MemMap.h"
uint8 EcuM_CheckRamHash(void)
{
	/* Begin Code EcuM_CheckRamHash */

    /* the RAM check always succeeds */
    return 1;

	/* End Code EcuM_CheckRamHash */

}
#define EcuM_CheckRamHash_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_CheckValidation
 *** 
 *** DESCRIPTION:
 ***     This callout is called by the EcuM to validate a wakeup source. If a valid wakeup has
 ***     been detected, it shall be reported to EcuM via EcuM_ValidateWakeupEvent().
 ***     
 ***     ServiceID  : 0x47
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType wakeupSource  
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_CheckValidation_START_SEC_CODE
#include "MemMap.h"
void EcuM_CheckValidation(EcuM_WakeupSourceType wakeupSource)
{
	/* Begin Code EcuM_CheckValidation */
#if (ECUM_WAKEUP_SUPPORT == STD_ON)
    int wakeupSourceId;
    for (wakeupSourceId = 0; wakeupSourceId < EcuM_PostBuildConfiguration->NumWakeupSources; wakeupSourceId++)
    {
        if ((wakeupSource & (1 << wakeupSourceId)) != 0)
        {
            EcuM_WakeupSourceConfig wakeupSourceConfig = EcuM_PostBuildConfiguration->WakeupSources[wakeupSourceId];
            if (wakeupSourceConfig.Configs == NULL)
            {
                continue;
            }

            {
                int i;
                for (i = 0; i < wakeupSourceConfig.NumConfigs; i++)
                {
#if (ECUM_CANIF_WAKEUP_VALIDATION_SUPPORT == STD_ON)
                    uint8 configType = wakeupSourceConfig.Configs[i].ConfigType;
                    if (configType == ECUM_WKSOURCE_TYPE_CAN || configType == ECUM_WKSOURCE_TYPE_CANTRCV)
                    {
                        /* only CAN requires validation */
                        CanIf_CheckValidation(1 << wakeupSourceId);
                    }
                    else
#endif
                    {
                        /* for all other wakeup sources, validate the event without check */
                        EcuM_ValidateWakeupEvent(1 << wakeupSourceId);
                    }
                }
            }
        }
    }
#endif
    ECUM_UNUSED_PARAMETER(wakeupSource);

    /* End Code EcuM_CheckValidation */

}
#define EcuM_CheckValidation_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_CheckWakeup
 *** 
 *** DESCRIPTION:
 ***     This callout is called by the EcuM to poll a wakeup source. It shall also be called
 ***     by the ISR of a wakeup source to set up the PLL and check other wakeup
 ***     sources that may be connected to the same interrupt.
 ***     
 ***     ServiceID  : 0x42
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType wakeupSource  
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_CheckWakeup_START_SEC_CODE
#include "MemMap.h"
void EcuM_CheckWakeup(EcuM_WakeupSourceType wakeupSource)
{
	/* Begin Code EcuM_CheckWakeup */
#if (ECUM_WAKEUP_SUPPORT == STD_ON)
    /* Adapt the implementation to your needs! */
    int wakeupSourceId, i;
    for (wakeupSourceId = 0; wakeupSourceId < EcuM_PostBuildConfiguration->NumWakeupSources; wakeupSourceId++)
    {
        if ((wakeupSource & (1 << wakeupSourceId)) != 0)
        {
            EcuM_WakeupSourceConfig wakeupSourceConfig = EcuM_PostBuildConfiguration->WakeupSources[wakeupSourceId];
            if (wakeupSourceConfig.Configs == NULL)
            {
                continue;
            }

            for (i = 0; i < wakeupSourceConfig.NumConfigs; i++)
            {
                switch (wakeupSourceConfig.Configs[i].ConfigType)
                {
#if (ECUM_INCLUDE_GPT == STD_ON && ECUM_GPT_WAKEUP_API_AVAILABLE == STD_ON)
                case ECUM_WKSOURCE_TYPE_GPT:
                    Gpt_CheckWakeup(1 << wakeupSourceId);
                    break;
#endif
#if (ECUM_INCLUDE_ICU == STD_ON && ECUM_ICU_CHECK_WAKEUP_API_AVAILABLE == STD_ON)
                case ECUM_WKSOURCE_TYPE_ICU:
                    Icu_CheckWakeup(1 << wakeupSourceId);
                    break;
#endif
#if (ECUM_INCLUDE_CANIF == STD_ON)
                case ECUM_WKSOURCE_TYPE_CAN:
                case ECUM_WKSOURCE_TYPE_CANTRCV:
#if (ECUM_CANIF_WAKEUP_SUPPORT == STD_ON)    
                    CanIf_CheckWakeup(1 << wakeupSourceId);
#else
                    EcuM_SetWakeupEvent(1 << wakeupSourceId);
#endif
                    break;
#endif
#if (ECUM_INCLUDE_LINIF == STD_ON)
                case ECUM_WKSOURCE_TYPE_LIN:
                case ECUM_WKSOURCE_TYPE_LINTRCV:
#if (ECUM_LINIF_WAKEUP_SUPPORT == STD_ON)
                    LinIf_CheckWakeup(1 << wakeupSourceId);
#else
                    EcuM_SetWakeupEvent(1 << wakeupSourceId);
#endif
                    break;
#endif
#if (ECUM_INCLUDE_FRIF == STD_ON)
                case ECUM_WKSOURCE_TYPE_FRTRCV:
                {
                    EcuM_FrWakeupSourceConfig *frConfig = &(((EcuM_FrWakeupSourceConfig*)EcuM_PostBuildConfiguration->FrWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                    FrIf_CheckWakeupByTransceiver(frConfig->ControllerIndex, frConfig->FrChannel);
                }
                break;
#endif
                }
            }
        }
    }
#endif

    ECUM_UNUSED_PARAMETER(wakeupSource);

	/* End Code EcuM_CheckWakeup */

}
#define EcuM_CheckWakeup_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_DeterminePbConfiguration
 *** 
 *** DESCRIPTION:
 ***     This callout should evaluate some condition, like port pin or NVRAM value, to
 ***     determine which post-build configuration shall be used in the remainder of
 ***     the startup process. It shall load this configuration data into a piece of
 ***     memory that is accessible by all BSW modules and shall return a pointer to
 ***     the EcuM post-build configuration as a base for all BSW module post-build
 ***     configrations.
 ***     
 ***     ServiceID  : 0x32
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    const EcuM_ConfigType*
\**************************************************************************************************/
#define EcuM_DeterminePbConfiguration_START_SEC_CODE
#include "MemMap.h"
const EcuM_ConfigType* EcuM_DeterminePbConfiguration(void)
{
	/* Begin Code EcuM_DeterminePbConfiguration */
    return &EcuM_DefaultPBConfig;
	/* End Code EcuM_DeterminePbConfiguration */

}
#define EcuM_DeterminePbConfiguration_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_DisableWakeupSources
 *** 
 *** DESCRIPTION:
 ***     The ECU Manager Module calls EcuM_DisableWakeupSources to set the wakeup source(s)
 ***     defined in the wakeupSource bitfield so that they are not able to wake the
 ***     ECU up.
 ***     
 ***     ServiceID  : 0x44
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType wakeupSource  
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_DisableWakeupSources_START_SEC_CODE
#include "MemMap.h"
void EcuM_DisableWakeupSources(EcuM_WakeupSourceType wakeupSource)
{
	/* Begin Code EcuM_DisableWakeupSources */
#if (ECUM_WAKEUP_SUPPORT == STD_ON)
    int wakeupSourceId, i;

    EcuM_WakeupSourceStatus.Enabled &= ~wakeupSource;

    /* Adapt the implementation to your need! */

    for (wakeupSourceId = 0; wakeupSourceId < EcuM_PostBuildConfiguration->NumWakeupSources; wakeupSourceId++)
    {
        if ((wakeupSource & (1 << wakeupSourceId)) != 0)
        {
            EcuM_WakeupSourceConfig wakeupSourceConfig = EcuM_PostBuildConfiguration->WakeupSources[wakeupSourceId];
            if (wakeupSourceConfig.Configs == NULL)
            {
                continue;
            }

            for (i = 0; i < wakeupSourceConfig.NumConfigs; i++)
            {
                switch (wakeupSourceConfig.Configs[i].ConfigType)
                {
#if (ECUM_INCLUDE_GPT == STD_ON && ECUM_GPT_WAKEUP_API_AVAILABLE == STD_ON)
                case ECUM_WKSOURCE_TYPE_GPT:
                    Gpt_DisableWakeup(((EcuM_GptWakeupSourceConfig*)EcuM_PostBuildConfiguration->GptWakeupSources)[wakeupSourceConfig.Configs[i].Index].Channel);
                    Gpt_SetMode(GPT_MODE_NORMAL);
                    break;
#endif
#if (ECUM_INCLUDE_ICU == STD_ON && ECUM_ICU_DISABLE_WAKEUP_API_AVAILABLE == STD_ON)
                case ECUM_WKSOURCE_TYPE_ICU:
                {
                    EcuM_IcuWakeupSourceConfig *icuConfig = &(((EcuM_IcuWakeupSourceConfig*)EcuM_PostBuildConfiguration->IcuWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                    Icu_DisableWakeup(icuConfig->Channel);
                }
                break;
#if (ECUM_INCLUDE_CANIF == STD_ON)
                case ECUM_WKSOURCE_TYPE_CANTRCV:
                    if (wakeupSourceConfig.RequiresPolling == FALSE)
                    {
                        EcuM_CanWakeupSourceConfig *canConfig = &(((EcuM_CanWakeupSourceConfig*)EcuM_PostBuildConfiguration->CanWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                        Icu_DisableWakeup(canConfig->IcuChannel);
                        CanIf_SetTrcvWakeupMode(canConfig->TransceiverId, CANTRCV_WUMODE_DISABLE);
                    }

                    /* in all other cases (polling, wakeup by CAN controller) nothing to do here */
                    break;
#endif
#if (ECUM_INCLUDE_LINIF == STD_ON)
                case ECUM_WKSOURCE_TYPE_LIN:
                case ECUM_WKSOURCE_TYPE_LINTRCV:
                    if (wakeupSourceConfig.RequiresPolling == FALSE)
                    {
                        EcuM_IcuWakeupSourceConfig *icuConfig = &(((EcuM_IcuWakeupSourceConfig*)EcuM_PostBuildConfiguration->IcuWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                        Icu_DisableWakeup(icuConfig->Channel);
                    }

                    /* in all other cases (polling, wakeup by LIN controller) nothing to do here */
                    break;
#endif
#if (ECUM_INCLUDE_ICU == STD_ON && ECUM_ICU_DISABLE_WAKEUP_API_AVAILABLE == STD_ON && ECUM_INCLUDE_FRTRCV == STD_ON)
                case ECUM_WKSOURCE_TYPE_FRTRCV:
                    if (wakeupSourceConfig.RequiresPolling == FALSE)
                    {
                        EcuM_FrWakeupSourceConfig *frConfig = &(((EcuM_FrWakeupSourceConfig*)EcuM_PostBuildConfiguration->FrWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                        Icu_DisableWakeup(frConfig->IcuChannel);
                    }

                    /* in all other cases (polling) nothing to be done here */
                    break;
#endif
#endif
                }
            }
        }
    }
#endif
    ECUM_UNUSED_PARAMETER(wakeupSource);

    /* End Code EcuM_DisableWakeupSources */

}
#define EcuM_DisableWakeupSources_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_EnableWakeupSources
 *** 
 *** DESCRIPTION:
 ***     The ECU Manager Module calls EcuM_EnableWakeupSource to allow the system designer to
 ***     notify wakeup sources defined in the wakeupSource bitfield that SLEEP will
 ***     be entered and to adjust their source accordingly.
 ***     
 ***     ServiceID  : 0x3f
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType wakeupSource  
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_EnableWakeupSources_START_SEC_CODE
#include "MemMap.h"
void EcuM_EnableWakeupSources(EcuM_WakeupSourceType wakeupSource)
{
	/* Begin Code EcuM_EnableWakeupSources */
#if (ECUM_WAKEUP_SUPPORT == STD_ON)
    int wakeupSourceId, i;

    /* Adapt the implementation to your need! */
    EcuM_WakeupSourceStatus.Enabled |= wakeupSource;

    for (wakeupSourceId = 0; wakeupSourceId < EcuM_PostBuildConfiguration->NumWakeupSources; wakeupSourceId++)
    {
        if ((wakeupSource & (1 << wakeupSourceId)) != 0)
        {
            EcuM_WakeupSourceConfig wakeupSourceConfig = EcuM_PostBuildConfiguration->WakeupSources[wakeupSourceId];
            if (wakeupSourceConfig.Configs == NULL)
            {
                continue;
            }

            for (i = 0; i < wakeupSourceConfig.NumConfigs; i++)
            {
                switch (wakeupSourceConfig.Configs[i].ConfigType)
                {
#if (ECUM_INCLUDE_GPT == STD_ON && ECUM_GPT_WAKEUP_API_AVAILABLE == STD_ON)
                case ECUM_WKSOURCE_TYPE_GPT:
                {
                    EcuM_GptWakeupSourceConfig *gptConfig = &(((EcuM_GptWakeupSourceConfig*)EcuM_PostBuildConfiguration->GptWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                    Gpt_EnableWakeup(gptConfig->Channel);
                    Gpt_StartTimer(gptConfig->Channel, gptConfig->Value);

                    Gpt_SetMode(GPT_MODE_SLEEP);
                }
                break;
#endif
#if (ECUM_INCLUDE_ICU == STD_ON && ECUM_ICU_ENABLE_WAKEUP_API_AVAILABLE == STD_ON)
                case ECUM_WKSOURCE_TYPE_ICU:
                {
                    EcuM_IcuWakeupSourceConfig *icuConfig = &(((EcuM_IcuWakeupSourceConfig*)EcuM_PostBuildConfiguration->IcuWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                    Icu_EnableWakeup(icuConfig->Channel);
                }
                break;
#if (ECUM_INCLUDE_CANIF == STD_ON)
                case ECUM_WKSOURCE_TYPE_CANTRCV:
                    if (wakeupSourceConfig.RequiresPolling == FALSE)
                    {
                        EcuM_CanWakeupSourceConfig *canConfig = &(((EcuM_CanWakeupSourceConfig*)EcuM_PostBuildConfiguration->CanWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                        CanIf_SetTrcvWakeupMode(canConfig->TransceiverId, CANTRCV_WUMODE_ENABLE);
                        Icu_EnableWakeup(canConfig->IcuChannel);
                    }

                    /* in all other cases (polling, wakeup by CAN controller)
                     * CanSM will have called CanIf_SetControllerMode or CanIf_SetTransceiverMode when going to sleep. */
                    break;
#endif
#if (ECUM_INCLUDE_LINIF == STD_ON)
                case ECUM_WKSOURCE_TYPE_LIN:
                case ECUM_WKSOURCE_TYPE_LINTRCV:
                    if (wakeupSourceConfig.RequiresPolling == FALSE)
                    {
                        EcuM_IcuWakeupSourceConfig *icuConfig = &(((EcuM_IcuWakeupSourceConfig*)EcuM_PostBuildConfiguration->IcuWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                        Icu_EnableWakeup(icuConfig->Channel);
                    }

                    /* in all other cases (polling, wakeup by LIN controller)
                     * LinSM will already have called LinIf_GotoSleep when changing to NO_COM state.
                     * In Sleep state the LIN Controller is wakeable or not by configuration. */
                    break;
#endif
#if (ECUM_INCLUDE_ICU == STD_ON && ECUM_ICU_ENABLE_WAKEUP_API_AVAILABLE == STD_ON && ECUM_INCLUDE_FRTRCV == STD_ON)
                case ECUM_WKSOURCE_TYPE_FRTRCV:
                    if (wakeupSourceConfig.RequiresPolling == FALSE)
                    {
                        EcuM_FrWakeupSourceConfig *frConfig = &(((EcuM_FrWakeupSourceConfig*)EcuM_PostBuildConfiguration->FrWakeupSources)[wakeupSourceConfig.Configs[i].Index]);
                        Icu_EnableWakeup(frConfig->IcuChannel);
                    }

                    /* in all other cases (polling) nothing to be done here */
                    break;
#endif
#endif
                }
            }
        }
    }
#endif

    ECUM_UNUSED_PARAMETER(wakeupSource);

    /* End Code EcuM_EnableWakeupSources */

}
#define EcuM_EnableWakeupSources_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_EndCheckWakeup
 *** 
 *** DESCRIPTION:
 ***     This API is called by any SW Module whose wakeup source is checked asynchronously
 ***     (e.g. asynchronous Can Trcv Driver) and the Check of the Wakeup returns a
 ***     negative Result (no Wakeup by this Source). The API cancels the
 ***     CheckWakeupTimer for the WakeupSource. If the correponding CheckWakeupTimer
 ***     is canceled the check of this wakeup source is finished.
 ***     
 ***     ServiceID  : 0x00
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType WakeupSource For this wakeup source the corresponding CheckWakeupTimer shall be canceled. 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_EndCheckWakeup_START_SEC_CODE
#include "MemMap.h"
void EcuM_EndCheckWakeup(EcuM_WakeupSourceType WakeupSource)
{
	/* Begin Code EcuM_EndCheckWakeup */
    /* Add your own implementation here! */
    ECUM_UNUSED_PARAMETER(WakeupSource);
	/* End Code EcuM_EndCheckWakeup */

}
#define EcuM_EndCheckWakeup_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_ErrorHook
 *** 
 *** DESCRIPTION:
 ***     The ECU State Manager will call the error hook if the error codes
 ***     \"ECUM_E_RAM_CHECK_FAILED\" or \"ECUM_E_CONFIGURATION_DATA_INCONSISTENT\"
 ***     occur. In this situation it is not possible to continue processing and the
 ***     ECU must be stopped. The integrator may choose the modality how the ECU is
 ***     stopped, i.e. reset, halt, restart, safe state etc.
 ***     
 ***     ServiceID  : 0x30
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	uint16 reason Reason for calling the error hook 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_ErrorHook_START_SEC_CODE
#include "MemMap.h"
void EcuM_ErrorHook(uint16 reason)
{
	/* Begin Code EcuM_ErrorHook */
    /* Add your own implementation here! */
    ECUM_UNUSED_PARAMETER(reason);
    /* End Code EcuM_ErrorHook */

}
#define EcuM_ErrorHook_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GenerateRamHash
 *** 
 *** DESCRIPTION:
 ***     see EcuM_CheckRamHash
 ***     
 ***     ServiceID  : 0x40
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_GenerateRamHash_START_SEC_CODE
#include "MemMap.h"
void EcuM_GenerateRamHash(void)
{
	/* Begin Code EcuM_GenerateRamHash */
	/* Add your own implementation here! */	
	/* End Code EcuM_GenerateRamHash */

}
#define EcuM_GenerateRamHash_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnEnterRun
 *** 
 *** DESCRIPTION:
 ***     On entry of RUN state is very similar to \"just after startup\". This call allows the
 ***     system designer to notify that RUN state has been reached.
 ***     
 ***     ServiceID  : 0x37
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_OnEnterRun_START_SEC_CODE
#include "MemMap.h"
void EcuM_OnEnterRun(void)
{
	/* Begin Code EcuM_OnEnterRun */
	/* Add your own implementation here! */	
	/* End Code EcuM_OnEnterRun */

}
#define EcuM_OnEnterRun_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnExitPostRun
 *** 
 *** DESCRIPTION:
 ***     This call allows the system designer to notify that the APP POST RUN state is about
 ***     to be left.
 ***     
 ***     ServiceID  : 0x39
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_OnExitPostRun_START_SEC_CODE
#include "MemMap.h"
void EcuM_OnExitPostRun(void)
{
	/* Begin Code EcuM_OnExitPostRun */
	/* Add your own implementation here! */	
	/* End Code EcuM_OnExitPostRun */

}
#define EcuM_OnExitPostRun_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnExitRun
 *** 
 *** DESCRIPTION:
 ***     This call allows the system designer to notify that the APP RUN state is about to be
 ***     left.
 ***     
 ***     ServiceID  : 0x38
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_OnExitRun_START_SEC_CODE
#include "MemMap.h"
void EcuM_OnExitRun(void)
{
	/* Begin Code EcuM_OnExitRun */
	/* Add your own implementation here! */	
	/* End Code EcuM_OnExitRun */

}
#define EcuM_OnExitRun_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnGoOffOne
 *** 
 *** DESCRIPTION:
 ***     This call allows the system designer to notify that the GO OFF I state is about to be
 ***     entered.
 ***     
 ***     ServiceID  : 0x3c
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_OnGoOffOne_START_SEC_CODE
#include "MemMap.h"
void EcuM_OnGoOffOne(void)
{
	/* Begin Code EcuM_OnGoOffOne */
	/* Add your own implementation here! */	
	/* End Code EcuM_OnGoOffOne */

}
#define EcuM_OnGoOffOne_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnGoOffTwo
 *** 
 *** DESCRIPTION:
 ***     This call allows the system designer to notify that the GO OFF II state is about to
 ***     be entered.
 ***     
 ***     ServiceID  : 0x3d
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_OnGoOffTwo_START_SEC_CODE
#include "MemMap.h"
void EcuM_OnGoOffTwo(void)
{
	/* Begin Code EcuM_OnGoOffTwo */
	/* Add your own implementation here! */	
	/* End Code EcuM_OnGoOffTwo */

}
#define EcuM_OnGoOffTwo_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnGoSleep
 *** 
 *** DESCRIPTION:
 ***     This call allows the system designer to notify that the GO SLEEP state is about to be
 ***     entered.
 ***     
 ***     ServiceID  : 0x3b
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_OnGoSleep_START_SEC_CODE
#include "MemMap.h"
void EcuM_OnGoSleep(void)
{
	/* Begin Code EcuM_OnGoSleep */
	/* Add your own implementation here! */	
	/* End Code EcuM_OnGoSleep */

}
#define EcuM_OnGoSleep_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnPrepShutdown
 *** 
 *** DESCRIPTION:
 ***     This call allows the system designer to notify that the PREP SHUTDOWN state is about
 ***     to be entered.
 ***     
 ***     ServiceID  : 0x3a
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_OnPrepShutdown_START_SEC_CODE
#include "MemMap.h"
void EcuM_OnPrepShutdown(void)
{
	/* Begin Code EcuM_OnPrepShutdown */
	/* Add your own implementation here! */	
	/* End Code EcuM_OnPrepShutdown */

}
#define EcuM_OnPrepShutdown_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnRTEStartup
 *** 
 *** DESCRIPTION:
 ***     
 ***     
 ***     ServiceID  : 0x36
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_OnRTEStartup_START_SEC_CODE
#include "MemMap.h"
void EcuM_OnRTEStartup(void)
{
	/* Begin Code EcuM_OnRTEStartup */
	/* Add your own implementation here! */	
	/* End Code EcuM_OnRTEStartup */

}
#define EcuM_OnRTEStartup_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_OnWakeupReaction
 *** 
 *** DESCRIPTION:
 ***     This callout gives the system designer the chance to intercept the automatic boot
 ***     behavior and to override the wakeup reaction computed from wakeup source.
 ***     
 ***     ServiceID  : 0x49
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupReactionType wact The wakeup reaction computed by ECU State Manager 
 *** 
 *** RETURNS:
 ***    EcuM_WakeupReactionType
\**************************************************************************************************/
#define EcuM_OnWakeupReaction_START_SEC_CODE
#include "MemMap.h"
EcuM_WakeupReactionType EcuM_OnWakeupReaction(EcuM_WakeupReactionType wact)
{
	/* Begin Code EcuM_OnWakeupReaction */

    /* Adapt the implementation to your needs! */
    /* do not alter the wakeup reaction by default */
    return wact;

	/* End Code EcuM_OnWakeupReaction */

}
#define EcuM_OnWakeupReaction_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_SleepActivity
 *** 
 *** DESCRIPTION:
 ***     This callout is invoked periodically in all reduced clock sleep modes. It is
 ***     explicitely allowed to poll wakeup sources from this callout and to call
 ***     wakeup notification functions to indicate the end of the sleep state to the
 ***     ECU State Manager.
 ***     
 ***     ServiceID  : 0x41
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_SleepActivity_START_SEC_CODE
#include "MemMap.h"
void EcuM_SleepActivity(void)
{
	/* Begin Code EcuM_SleepActivity */
    /* Add your own implementation here! */
    /* End Code EcuM_SleepActivity */

}
#define EcuM_SleepActivity_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_StartCheckWakeup
 *** 
 *** DESCRIPTION:
 ***     This API is called by the ECU Firmware to start the CheckWakeupTimer for the
 ***     corresponding WakeupSource. If EcuMCheckWakeupTimeout ' 0 the
 ***     CheckWakeupTimer for the WakeupSource is started. If EcuMCheckWakeupTimeout
 ***     '= 0 the API call is ignored by the EcuM.
 ***     
 ***     ServiceID  : 0x00
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType WakeupSource For this wakeup source the corresponding CheckWakeupTimer shall be started. 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_StartCheckWakeup_START_SEC_CODE
#include "MemMap.h"
void EcuM_StartCheckWakeup(EcuM_WakeupSourceType WakeupSource)
{
	/* Begin Code EcuM_StartCheckWakeup */
    /* Add your own implementation here! */
    ECUM_UNUSED_PARAMETER(WakeupSource);
    /* End Code EcuM_StartCheckWakeup */

}
#define EcuM_StartCheckWakeup_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_StartWakeupSources
 *** 
 *** DESCRIPTION:
 ***     The callout shall start the given wakeup source(s) so that they are ready to perform
 ***     wakeup validation.
 ***     
 ***     ServiceID  : 0x46
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType wakeupSource  
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_StartWakeupSources_START_SEC_CODE
#include "MemMap.h"
void EcuM_StartWakeupSources(EcuM_WakeupSourceType wakeupSource)
{
	/* Begin Code EcuM_StartWakeupSources */
    /* Add your own implementation here! */
    ECUM_UNUSED_PARAMETER(wakeupSource);
    /* End Code EcuM_StartWakeupSources */

}
#define EcuM_StartWakeupSources_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_StopWakeupSources
 *** 
 *** DESCRIPTION:
 ***     The callout shall stop the given wakeup source(s) after unsuccessful wakeup
 ***     validation.
 ***     
 ***     ServiceID  : 0x48
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType wakeupSource  
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_StopWakeupSources_START_SEC_CODE
#include "MemMap.h"
void EcuM_StopWakeupSources(EcuM_WakeupSourceType wakeupSource)
{
	/* Begin Code EcuM_StopWakeupSources */
    /* Add your own implementation here! */
    ECUM_UNUSED_PARAMETER(wakeupSource);
    /* End Code EcuM_StopWakeupSources */

}
#define EcuM_StopWakeupSources_STOP_SEC_CODE
#include "MemMap.h"


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ECUM_CALLOUT_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
