/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcuConfiguration_EcuInstance1
 *** Codefile            : EcuM.c
 ***
 *** Generated by SystemDesk 5.6.0.13023
 *** Generation date: 2025-06-11 08:50:22
 ***
 *** Copyright (c) 2018 dSPACE GmbH
\**************************************************************************************************/

#ifndef ECUM_C
#define ECUM_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/
#include "EcuM.h"
#include "MemMap.h"
#include "Rte_EcuM.h"
#include "EcuM_Cbk.h"
#include "EcuM_Callout.h"

/* Begin Code InternalIncludes */
#include "EcuM_Internal.h"
/* End Code InternalIncludes */ 

/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/


#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */

/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  VARIABLE DECLARATIONS
\*------------------------------------------------------------------------------------------------*/
EcuM_ShutdownTargetType EcuM_ShutdownTarget = { ECUM_STATE_OFF, 0 };

EcuM_ShutdownTargetType EcuM_LastShutdownTarget = { ECUM_STATE_OFF, 0 };

static EcuM_BootTargetType EcuM_BootTarget = ECUM_BOOT_TARGET_APP;

boolean EcuM_AllRunRequestsKilled = FALSE;

boolean EcuM_AllPostRunRequestsKilled = FALSE;

EcuM_StateType EcuM_CurrentState = ECUM_STATE_OFF;

uint8 EcuM_CurrentNumberOfRunRequests;

uint8 EcuM_CurrentNumberOfPostRunRequests;

boolean EcuM_CurrentRunRequests[1];

boolean EcuM_CurrentPostRunRequests[1];

EcuM_InitListEntryType EcuM_InitListZeroEntries[1];

EcuM_InitListType EcuM_InitListZero = { &EcuM_InitListZeroEntries[0], 0 };


uint8 EcuM_NextMode;


/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
*** TASK:
***     EcuM_StartupTwoTask
***
*** DESCRIPTION:
***     Performs the initialization of the startup
\**************************************************************************************************/
TASK(EcuM_StartupTwoTask)
{
    EcuM_StartupTwo();

    TerminateTask();
}

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_MainFunction
 *** 
 *** DESCRIPTION:
 ***     The purpose of this service is to implement all activities of the ECU State Manager
 ***     while the OS is up and running.
 ***     
 ***     ServiceID  : 0x18
 ***     Reentrant  : false

 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_MainFunction_START_SEC_CODE
#include "MemMap.h"
void EcuM_MainFunction(void)
{
    /* Begin Code EcuM_MainFunction */
    
    /* Error checks. */
    if (EcuM_CheckInitialized(ECUM_MAIN_FUNCTION_SERVICE_ID) == E_NOT_OK)
    {
        return;
    }

    /* EcuM state machine. */
    switch (EcuM_CurrentState)
    {
    case ECUM_STATE_STARTUP:
        break;
    case ECUM_STATE_STARTUP_ONE:
        break;
    case ECUM_STATE_STARTUP_TWO:
        /* call EcuM_DoStartupII until the timeout for NvMReadAll expires */
        EcuM_DoStartupII();
        break;
    case ECUM_STATE_WAKEUP:
        break;
    case ECUM_STATE_WAKEUP_ONE:
        break;
    case ECUM_STATE_WAKEUP_VALIDATION:
        EcuM_DoWakeupValidation();
        break;
    case ECUM_STATE_WAKEUP_REACTION:
        EcuM_DoWakeupReaction();
        break;
    case ECUM_STATE_WAKEUP_TWO:
        EcuM_DoWakeupII();
        break;
    case ECUM_STATE_WAKEUP_WAKESLEEP:
        break;
    case ECUM_STATE_WAKEUP_TTII:
        break;
    case ECUM_STATE_RUN:
        EcuM_DoRunII();
        break;
    case ECUM_STATE_APP_RUN:
        EcuM_DoRunII();
        break;
    case ECUM_STATE_APP_POST_RUN:
        EcuM_DoRunIII();
        break;
    case ECUM_STATE_SHUTDOWN:
        break;
    case ECUM_STATE_PREP_SHUTDOWN:
        EcuM_DoPrepShutdown();
        break;
    case ECUM_STATE_GO_SLEEP:
        EcuM_DoGoSleep();
        break;
    case ECUM_STATE_GO_OFF_ONE:
        EcuM_DoGoOffI();
        break;
    case ECUM_STATE_GO_OFF_TWO:
        break;
    case ECUM_STATE_SLEEP:
        break;
    case ECUM_STATE_RESET:
        break;
    case ECUM_STATE_OFF:
        break;
    default:
        break;
    }
    /* End Code EcuM_MainFunction */

}
#define EcuM_MainFunction_STOP_SEC_CODE
#include "MemMap.h"


/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_ClearWakeupEvent
 *** 
 *** DESCRIPTION:
 ***     Clears wakeup events.
 ***     
 ***     ServiceID  : 0x16
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_WakeupSourceType sources Events to be cleared
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_ClearWakeupEvent_START_SEC_CODE
#include "MemMap.h"
void EcuM_ClearWakeupEvent(EcuM_WakeupSourceType sources)
{

    /* Begin Code EcuM_ClearWakeupEvent */
    EcuM_CurrentWakeupEvent &= ~sources;
    EcuM_WakeupSourceStatus.Pending &= ~sources;
    EcuM_WakeupSourceStatus.Valid &= ~sources;
    EcuM_WakeupSourceStatus.Expired &= ~sources;
    /* End Code EcuM_ClearWakeupEvent */

}
#define EcuM_ClearWakeupEvent_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GetBootTarget
 *** 
 *** DESCRIPTION:
 ***     EcuM_GetBootTarget returns the current boot target - see EcuM_SelectBootTarget.
 ***     EcuM_GetBootTarget is part of the ECU Manager Module port interface.
 ***     
 ***     ServiceID  : 0x13
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_BootTargetType* target The currently selected boot target.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_GetBootTarget_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_GetBootTarget(EcuM_BootTargetType* target)
{

    /* Begin Code EcuM_GetBootTarget */

    /* [SWS_EcuMf_00035] Parameter target of the function EcuM_GetBootTarget : An implementation shall cope
       with NULL pointers by simply ignoring the out parameter in all cases. */
    if (target != NULL)
    {
        *target = EcuM_BootTarget;
    }

    return E_OK;

    /* End Code EcuM_GetBootTarget */

}
#define EcuM_GetBootTarget_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GetExpiredWakeupEvents
 *** 
 *** DESCRIPTION:
 ***     Gets expired wakeup events.
 ***     
 ***     ServiceID  : 0x19
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    EcuM_WakeupSourceType
\**************************************************************************************************/
#define EcuM_GetExpiredWakeupEvents_START_SEC_CODE
#include "MemMap.h"
EcuM_WakeupSourceType EcuM_GetExpiredWakeupEvents(void)
{

    /* Begin Code EcuM_GetExpiredWakeupEvents */
    return EcuM_WakeupSourceStatus.Expired;
    /* End Code EcuM_GetExpiredWakeupEvents */

}
#define EcuM_GetExpiredWakeupEvents_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GetLastShutdownTarget
 *** 
 *** DESCRIPTION:
 ***     EcuM_GetLastShutdownTarget returns the shutdown target of the previous shutdown
 ***     process. EcuM_GetLastShutdownTarget is part of the ECU Manager Module port
 ***     interface.
 ***     
 ***     ServiceID  : 0x08
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_StateType* shutdownTarget One of these values is returned: *      ECUM_STATE_SLEEP *      ECUM_STATE_RESET *
 ***     ECUM_STATE_OFF
 ***    uint8* sleepMode If the out parameter \"shutdownTarget\" is ECUM_STATE_SLEEP, sleepMode tells which of
 ***     the configured sleep modes was actually chosen. If \"shutdownTarget\" is
 ***     ECUM_STATE_RESET, sleepMode tells which of the configured reset modes was
 ***     actually chosen.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_GetLastShutdownTarget_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_GetLastShutdownTarget(EcuM_StateType* shutdownTarget, uint8* sleepMode)
{

    /* Begin Code EcuM_GetLastShutdownTarget */
    Std_ReturnType result;

    /* Error checks. */
    if (EcuM_CheckInitialized(ECUM_GET_LAST_SHUTDOWN_TARGET_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    /* check for NULL pointer */
    result = EcuM_CheckNullPtr(ECUM_GET_LAST_SHUTDOWN_TARGET_SERVICE_ID, shutdownTarget);

    if (shutdownTarget != NULL)
    {
        *shutdownTarget = EcuM_LastShutdownTarget.state;

        if (EcuM_LastShutdownTarget.state == ECUM_STATE_SLEEP)
        {
            /* check for NULL pointer only if parameter must be set */
            result = EcuM_CheckNullPtr(ECUM_GET_LAST_SHUTDOWN_TARGET_SERVICE_ID, sleepMode);
            if (sleepMode != NULL)
            {
                *sleepMode = EcuM_LastShutdownTarget.mode;
            }
        }
    }

    return result;

    /* End Code EcuM_GetLastShutdownTarget */

}
#define EcuM_GetLastShutdownTarget_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GetPendingWakeupEvents
 *** 
 *** DESCRIPTION:
 ***     Gets pending wakeup events.
 ***     
 ***     ServiceID  : 0x0d
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    EcuM_WakeupSourceType
\**************************************************************************************************/
#define EcuM_GetPendingWakeupEvents_START_SEC_CODE
#include "MemMap.h"
EcuM_WakeupSourceType EcuM_GetPendingWakeupEvents(void)
{

    /* Begin Code EcuM_GetPendingWakeupEvents */
    DisableAllInterrupts();

    if (EcuM_CurrentWakeupEvent != 0)
    {
        EcuM_WakeupSourceStatus.Pending = EcuM_CurrentWakeupEvent & EcuM_WakeupSourceStatus.Enabled;
        EcuM_CurrentWakeupEvent = 0;
    }

    EnableAllInterrupts();

    return EcuM_WakeupSourceStatus.Pending;
    /* End Code EcuM_GetPendingWakeupEvents */

}
#define EcuM_GetPendingWakeupEvents_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GetShutdownTarget
 *** 
 *** DESCRIPTION:
 ***     EcuM_GetShutdownTarget returns the currently selected shutdown target as set by
 ***     EcuM_SelectShutdownTarget. EcuM_GetShutdownTarget is part of the ECU Manager
 ***     Module port interface.
 ***     
 ***     ServiceID  : 0x09
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_StateType* shutdownTarget One of these values is returned: *      ECUM_STATE_SLEEP *      ECUM_STATE_RESET *
 ***     ECUM_STATE_OFF
 ***    uint8* sleepMode If the out parameter \"shutdownTarget\" is ECUM_STATE_SLEEP, sleepMode tells which of
 ***     the configured sleep modes was actually chosen. If \"shutdownTarget\" is
 ***     ECUM_STATE_RESET, sleepMode tells which of the configured reset modes was
 ***     actually chosen.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_GetShutdownTarget_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_GetShutdownTarget(EcuM_StateType* shutdownTarget, uint8* sleepMode)
{

    /* Begin Code EcuM_GetShutdownTarget */
    Std_ReturnType result;

    /* Error checks. */
    if (EcuM_CheckInitialized(ECUM_GET_SHUTDOWN_TARGET_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    /* check for NULL pointer */
    result = EcuM_CheckNullPtr(ECUM_GET_SHUTDOWN_TARGET_SERVICE_ID, shutdownTarget);

    if (shutdownTarget != NULL)
    {
        *shutdownTarget = EcuM_ShutdownTarget.state;

        if (EcuM_ShutdownTarget.state == ECUM_STATE_SLEEP)
        {
            /* check for NULL pointer only if parameter must be set */
            result = EcuM_CheckNullPtr(ECUM_GET_SHUTDOWN_TARGET_SERVICE_ID, sleepMode);
            if (sleepMode != NULL)
            {
                *sleepMode = EcuM_ShutdownTarget.mode;
            }
        }
    }

    return result;

    /* End Code EcuM_GetShutdownTarget */

}
#define EcuM_GetShutdownTarget_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GetState
 *** 
 *** DESCRIPTION:
 ***     Gets a state.
 ***     
 ***     ServiceID  : 0x07
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_StateType* state The value of the internal state variable.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_GetState_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_GetState(EcuM_StateType* state)
{

    /* Begin Code EcuM_GetState */

    /* Error checks. */
    if (EcuM_CheckInitialized(ECUM_GET_STATE_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    if (EcuM_CheckNullPtr(ECUM_GET_STATE_SERVICE_ID, state) != E_OK)
    {
        return E_NOT_OK;
    }

    *state = EcuM_CurrentState;

    return E_OK;

    /* End Code EcuM_GetState */

}
#define EcuM_GetState_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GetStatusOfWakeupSource
 *** 
 *** DESCRIPTION:
 ***     The sum status shall be computed according to the following algorithm: If
 ***     (EcuM_GetValidatedWakeupEvents() AND sources) is not 0 then return
 ***     ECUM_WKSTATUS_VALIDATED. If (EcuM_GetPendingWakeupEvents() AND sources) is
 ***     not 0 then return ECUM_WKSTATUS_PENDING. If (EcuM_GetExpiredWakeupEvents()
 ***     AND sources) is not 0 then return ECUM_WKSTATUS_EXPIRED. Otherwise, return
 ***     ECUM_WKSTATUS_NONE.
 ***     
 ***     ServiceID  : 0x17
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_WakeupSourceType sources The sources for which the status is returned
 *** 
 *** RETURNS:
 ***    EcuM_WakeupStatusType
\**************************************************************************************************/
#define EcuM_GetStatusOfWakeupSource_START_SEC_CODE
#include "MemMap.h"
EcuM_WakeupStatusType EcuM_GetStatusOfWakeupSource(EcuM_WakeupSourceType sources)
{

    /* Begin Code EcuM_GetStatusOfWakeupSource */
    if ((EcuM_GetValidatedWakeupEvents() & sources) != 0)
    {
        return ECUM_WKSTATUS_VALIDATED;
    }
    if ((EcuM_GetPendingWakeupEvents() & sources) != 0)
    {
        return ECUM_WKSTATUS_PENDING;
    }
    if ((EcuM_GetExpiredWakeupEvents() & sources) != 0)
    {
        return ECUM_WKSTATUS_EXPIRED;
    }
    return ECUM_WKSTATUS_NONE;
    /* End Code EcuM_GetStatusOfWakeupSource */

}
#define EcuM_GetStatusOfWakeupSource_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_GetValidatedWakeupEvents
 *** 
 *** DESCRIPTION:
 ***     Gets validated wakeup events.
 ***     
 ***     ServiceID  : 0x15
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    EcuM_WakeupSourceType
\**************************************************************************************************/
#define EcuM_GetValidatedWakeupEvents_START_SEC_CODE
#include "MemMap.h"
EcuM_WakeupSourceType EcuM_GetValidatedWakeupEvents(void)
{

    /* Begin Code EcuM_GetValidatedWakeupEvents */
    return EcuM_WakeupSourceStatus.Valid;
    /* End Code EcuM_GetValidatedWakeupEvents */

}
#define EcuM_GetValidatedWakeupEvents_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_Init
 *** 
 *** DESCRIPTION:
 ***     Initializes the ECU state manager and carries out the startup procedure. The function
 ***     will never return (it calls StartOS)
 ***     
 ***     ServiceID  : 0x01
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_Init_START_SEC_CODE
#include "MemMap.h"
void EcuM_Init(void)
{

    /* Begin Code EcuM_Init */
    int i;
    for (i = 0; i < EcuMConf_EcuMFixedUserConfig_LENGTH; i++)
    {
        EcuM_CurrentRunRequests[i] = FALSE;
        EcuM_CurrentPostRunRequests[i] = FALSE;
    }

    EcuM_CurrentNumberOfRunRequests = 0;
    EcuM_CurrentNumberOfPostRunRequests = 0;

    EcuM_SwitchState(ECUM_STATE_STARTUP_ONE, FALSE);

    EcuM_AllRunRequestsKilled = FALSE;
    EcuM_AllPostRunRequestsKilled = FALSE;

    EcuM_WakeupSourceStatus.Enabled = 0;
    EcuM_WakeupSourceStatus.Expired = 0;
    EcuM_WakeupSourceStatus.Pending = 0;
    EcuM_WakeupSourceStatus.Valid = 0;

    EcuM_DoStartupI();

    /* End Code EcuM_Init */

}
#define EcuM_Init_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_KillAllPostRUNRequests
 *** 
 *** DESCRIPTION:
 ***     This function unconditionally releases all pending requests to PostRUN.
 ***     
 ***     ServiceID  : 0x2a
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_KillAllPostRUNRequests_START_SEC_CODE
#include "MemMap.h"
void EcuM_KillAllPostRUNRequests(void)
{

    /* Begin Code EcuM_KillAllPostRUNRequests */
    int i;
    EcuM_AllPostRunRequestsKilled = TRUE;
    EcuM_CurrentNumberOfPostRunRequests = 0;
    for (i = 0; i < EcuMConf_EcuMFixedUserConfig_LENGTH; i++)
    {
        EcuM_CurrentPostRunRequests[i] = FALSE;
    }
    /* End Code EcuM_KillAllPostRUNRequests */

}
#define EcuM_KillAllPostRUNRequests_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_KillAllRUNRequests
 *** 
 *** DESCRIPTION:
 ***     The benefit of this function over an ECU reset is that the shutdown sequence is
 ***     executed, which e.g. takes care of writing back NV memory contents.
 ***     
 ***     ServiceID  : 0x05
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_KillAllRUNRequests_START_SEC_CODE
#include "MemMap.h"
void EcuM_KillAllRUNRequests(void)
{

    /* Begin Code EcuM_KillAllRUNRequests */
    int i;
    EcuM_AllRunRequestsKilled = TRUE;
    EcuM_CurrentNumberOfRunRequests = 0;
    for (i = 0; i < EcuMConf_EcuMFixedUserConfig_LENGTH; i++)
    {
        EcuM_CurrentRunRequests[i] = FALSE;
    }

    EcuM_Det_ReportError(ECUM_KILL_ALL_R_U_N_REQUESTS_SERVICE_ID, ECUM_E_ALL_RUN_REQUESTS_KILLED);

    /* End Code EcuM_KillAllRUNRequests */

}
#define EcuM_KillAllRUNRequests_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_ReleasePOST_RUN
 *** 
 *** DESCRIPTION:
 ***     Releases a POST RUN request previously done with a call to EcuM_RequestPOST_RUN. The
 ***     service is intended for implementing AUTOSAR ports.
 ***     
 ***     ServiceID  : 0x0b
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_UserType user ID of the entity releasing the POST RUN state.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_ReleasePOST_RUN_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_ReleasePOST_RUN(EcuM_UserType user)
{

    /* Begin Code EcuM_ReleasePOST_RUN */
    if (EcuM_CheckInitialized(ECUM_RELEASE_P_O_S_T_R_U_N_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    if (user >= EcuMConf_EcuMFixedUserConfig_LENGTH)
    {
        /* invalid user ID */
        return E_NOT_OK;
    }

    if (EcuM_CurrentPostRunRequests[user] == FALSE)
    {
        /* multiple run requests from the same user */
        EcuM_Det_ReportError(ECUM_RELEASE_P_O_S_T_R_U_N_SERVICE_ID, ECUM_E_MISMATCHED_RUN_RELEASE);
        return E_NOT_OK;
    }

    EcuM_CurrentPostRunRequests[user] = FALSE;
    EcuM_CurrentNumberOfPostRunRequests--;

    return E_OK;

    /* End Code EcuM_ReleasePOST_RUN */

}
#define EcuM_ReleasePOST_RUN_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_ReleaseRUN
 *** 
 *** DESCRIPTION:
 ***     Releases a RUN request previously done with a call to EcuM_RequestRUN. The service is
 ***     intended for implementing AUTOSAR ports.
 ***     
 ***     ServiceID  : 0x04
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_UserType user ID of the entity releasing the RUN state.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_ReleaseRUN_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_ReleaseRUN(EcuM_UserType user)
{

    /* Begin Code EcuM_ReleaseRUN */
    if (EcuM_CheckInitialized(ECUM_RELEASE_R_U_N_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    if (user >= EcuMConf_EcuMFixedUserConfig_LENGTH)
    {
        /* invalid user ID */
        return E_NOT_OK;
    }

    if (EcuM_CurrentRunRequests[user] == FALSE)
    {
        /* multiple release run requests from the same user */
        EcuM_Det_ReportError(ECUM_RELEASE_R_U_N_SERVICE_ID, ECUM_E_MISMATCHED_RUN_RELEASE);
        return E_NOT_OK;
    }

    EcuM_CurrentRunRequests[user] = FALSE;
    EcuM_CurrentNumberOfRunRequests--;

    return E_OK;

    /* End Code EcuM_ReleaseRUN */

}
#define EcuM_ReleaseRUN_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_RequestPOST_RUN
 *** 
 *** DESCRIPTION:
 ***     Places a request for the POST RUN state. Requests can be placed by every user made
 ***     known to the state manager at configuration time. Requests for RUN and POST
 ***     RUN must be tracked independently (in other words: two independent
 ***     variables). The service is intended for implementing AUTOSAR ports.
 ***     
 ***     ServiceID  : 0x0a
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_UserType user ID of the entity requesting the POST RUN state.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_RequestPOST_RUN_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_RequestPOST_RUN(EcuM_UserType user)
{

    /* Begin Code EcuM_RequestPOST_RUN */
    if (EcuM_CheckInitialized(ECUM_REQUEST_P_O_S_T_R_U_N_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    if (EcuM_AllPostRunRequestsKilled == TRUE)
    {
        EcuM_Det_ReportError(ECUM_REQUEST_P_O_S_T_R_U_N_SERVICE_ID, ECUM_E_ALL_RUN_REQUESTS_KILLED);
        return E_NOT_OK;
    }

    /* check for invalid user ID and whether EcuM_KillAllPostRUNRequests has been invoked */
    if (user >= EcuMConf_EcuMFixedUserConfig_LENGTH)
    {
        EcuM_Det_ReportError(ECUM_REQUEST_P_O_S_T_R_U_N_SERVICE_ID, ECUM_E_INVALID_PAR);
        return E_NOT_OK;
    }

    if (EcuM_CurrentPostRunRequests[user] == TRUE)
    {
        /* multiple run requests from the same user */
        EcuM_Det_ReportError(ECUM_REQUEST_P_O_S_T_R_U_N_SERVICE_ID, ECUM_E_MULTIPLE_RUN_REQUESTS);
        return E_NOT_OK;
    }

    EcuM_CurrentPostRunRequests[user] = TRUE;
    EcuM_CurrentNumberOfPostRunRequests++;

    return E_OK;

    /* End Code EcuM_RequestPOST_RUN */

}
#define EcuM_RequestPOST_RUN_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_RequestRUN
 *** 
 *** DESCRIPTION:
 ***     Places a request for the RUN state. Requests can be placed by every user made known
 ***     to the state manager at configuration time.
 ***     
 ***     ServiceID  : 0x03
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_UserType user ID of the entity requesting the RUN state.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_RequestRUN_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_RequestRUN(EcuM_UserType user)
{

    /* Begin Code EcuM_RequestRUN */
    if (EcuM_CheckInitialized(ECUM_REQUEST_R_U_N_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    if (EcuM_AllRunRequestsKilled == TRUE)
    {
        EcuM_Det_ReportError(ECUM_REQUEST_R_U_N_SERVICE_ID, ECUM_E_ALL_RUN_REQUESTS_KILLED);
        return E_NOT_OK;
    }

    /* check for invalid user ID and whether EcuM_KillAllRUNRequests has been invoked */
    if (user >= EcuMConf_EcuMFixedUserConfig_LENGTH)
    {
        /* invalid user ID */
        EcuM_Det_ReportError(ECUM_REQUEST_R_U_N_SERVICE_ID, ECUM_E_INVALID_PAR);
        return E_NOT_OK;
    }

    if (EcuM_CurrentRunRequests[user] == TRUE)
    {
        /* multiple run requests from the same user */
        EcuM_Det_ReportError(ECUM_REQUEST_R_U_N_SERVICE_ID, ECUM_E_MULTIPLE_RUN_REQUESTS);
        return E_NOT_OK;
    }

    EcuM_CurrentRunRequests[user] = TRUE;
    EcuM_CurrentNumberOfRunRequests++;
    EcuM_RunRequestTimeout = 0;
    EcuM_UseMinimumMode = STD_OFF;

    return E_OK;

    /* End Code EcuM_RequestRUN */

}
#define EcuM_RequestRUN_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_SelectBootTarget
 *** 
 *** DESCRIPTION:
 ***     EcuM_SelectBootTarget selects a boot target. EcuM_SelectBootTarget is part of the ECU
 ***     Manager Module port interface.
 ***     
 ***     ServiceID  : 0x12
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_BootTargetType target The selected boot target.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_SelectBootTarget_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_SelectBootTarget(EcuM_BootTargetType target)
{

    /* Begin Code EcuM_SelectBootTarget */

    /* Error checks. */
    if (EcuM_CheckInitialized(ECUM_SELECT_BOOT_TARGET_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    EcuM_BootTarget = target;

    return E_OK;

    /* End Code EcuM_SelectBootTarget */

}
#define EcuM_SelectBootTarget_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_SelectShutdownTarget
 *** 
 *** DESCRIPTION:
 ***     EcuM_SelectShutdownTarget selects the shutdown target. EcuM_SelectShutdownTarget is
 ***     part of the ECU Manager Module port interface.
 ***     
 ***     ServiceID  : 0x06
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_StateType target The selected shutdown target.
 ***    uint8 mode The identfier of a sleep mode (if target is ECUM_STATE_SLEEP) or a reset mechanism
 ***     (if target is ECUM_STATE_RESET) as defined by configuration.
 *** 
 *** RETURNS:
 ***    Std_ReturnType
\**************************************************************************************************/
#define EcuM_SelectShutdownTarget_START_SEC_CODE
#include "MemMap.h"
Std_ReturnType EcuM_SelectShutdownTarget(EcuM_StateType target, uint8 mode)
{

    /* Begin Code EcuM_SelectShutdownTarget */

    /* Error checks. */
    if (EcuM_CheckInitialized(ECUM_SELECT_SHUTDOWN_TARGET_SERVICE_ID) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    if (EcuM_CheckValidShutdownTarget(ECUM_SELECT_SHUTDOWN_TARGET_SERVICE_ID, target) == E_NOT_OK)
    {
        return E_NOT_OK;
    }

    if (target == ECUM_STATE_SLEEP && mode > EcuM_PostBuildConfiguration->NumSleepModes)
    {
        return E_NOT_OK;
    }

    EcuM_ShutdownTarget.state = target;
    EcuM_ShutdownTarget.mode = mode;

    return E_OK;

    /* End Code EcuM_SelectShutdownTarget */

}
#define EcuM_SelectShutdownTarget_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_Shutdown
 *** 
 *** DESCRIPTION:
 ***     Typically called from the shutdown hook, this function takes over execution control
 ***     and will carry out GO OFF II activities.
 ***     
 ***     ServiceID  : 0x02
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_Shutdown_START_SEC_CODE
#include "MemMap.h"
void EcuM_Shutdown(void)
{

    /* Begin Code EcuM_Shutdown */
    EcuM_LastShutdownTarget = EcuM_ShutdownTarget;
    EcuM_DoGoOffII();
    /* End Code EcuM_Shutdown */

}
#define EcuM_Shutdown_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_StartupTwo
 *** 
 *** DESCRIPTION:
 ***     This function implements the STARTUP II state.
 ***     
 ***     ServiceID  : 0x1a
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***     -/-
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_StartupTwo_START_SEC_CODE
#include "MemMap.h"
void EcuM_StartupTwo(void)
{

    /* Begin Code EcuM_StartupTwo */
    EcuM_DoStartupII();
    /* End Code EcuM_StartupTwo */

}
#define EcuM_StartupTwo_STOP_SEC_CODE
#include "MemMap.h"


/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_CB_NfyNvMJobEnd
 *** 
 *** DESCRIPTION:
 ***     Used to notify about the end of NVRAM jobs initiated by EcuM The callback must be
 ***     callable from normal and interrupt execution contexts.
 ***     
 ***     ServiceID  : 0x65
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    uint8 ServiceId Unique Service ID of NVRAM manager service.
 ***    uint8 JobResult Covers the job result of the previous processed multi block job.
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_CB_NfyNvMJobEnd_START_SEC_CODE
#include "MemMap.h"
void EcuM_CB_NfyNvMJobEnd(uint8 ServiceId, uint8 JobResult)
{

    /* Begin Code EcuM_CB_NfyNvMJobEnd */
#if (ECUM_INCLUDE_NVM == STD_ON)
    if ((ServiceId == NVM_READ_ALL_SERVICE_ID || ServiceId == NVM_WRITE_ALL_SERVICE_ID) && JobResult == E_OK)
    {
        EcuM_NvMCbReceived = TRUE;
    }
#else
    ECUM_UNUSED_PARAMETER(ServiceId);
    ECUM_UNUSED_PARAMETER(JobResult);
#endif
    /* End Code EcuM_CB_NfyNvMJobEnd */

}
#define EcuM_CB_NfyNvMJobEnd_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_SetWakeupEvent
 *** 
 *** DESCRIPTION:
 ***     Sets the wakeup event.
 ***     
 ***     ServiceID  : 0x0c
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_WakeupSourceType sources Value to be set
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_SetWakeupEvent_START_SEC_CODE
#include "MemMap.h"
void EcuM_SetWakeupEvent(EcuM_WakeupSourceType sources)
{

    /* Begin Code EcuM_SetWakeupEvent */
    EcuM_WakeupSourceStatus.Pending |= sources & EcuM_PostBuildConfiguration->SleepModes[EcuM_ShutdownTarget.mode].WakeupSourceMask;
    /* End Code EcuM_SetWakeupEvent */

}
#define EcuM_SetWakeupEvent_STOP_SEC_CODE
#include "MemMap.h"

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_ValidateWakeupEvent
 *** 
 *** DESCRIPTION:
 ***     After wakeup, the ECU State Manager will stop the process during the WAKEUP
 ***     VALIDATION state/sequence to wait for validation of the wakeup event.This
 ***     API service is used to indicate to the ECU Manager module that the wakeup
 ***     events indicated in the sources parameter have been validated.
 ***     
 ***     ServiceID  : 0x14
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***    EcuM_WakeupSourceType sources Events that have been validated
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
#define EcuM_ValidateWakeupEvent_START_SEC_CODE
#include "MemMap.h"
void EcuM_ValidateWakeupEvent(EcuM_WakeupSourceType sources)
{

    /* Begin Code EcuM_ValidateWakeupEvent */
    EcuM_WakeupSourceStatus.Valid |= (sources & EcuM_WakeupSourceStatus.Pending);
    /* End Code EcuM_ValidateWakeupEvent */

}
#define EcuM_ValidateWakeupEvent_STOP_SEC_CODE
#include "MemMap.h"


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 

#endif /* ECUM_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
