/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcuConfiguration_EcuInstance1
 *** Codefile            : EcuM_Cbk.h
 ***
 *** Generated by SystemDesk 5.6.0.13023
 *** Generation date: 2025-06-11 08:50:22
 ***
 *** Copyright (c) 2018 dSPACE GmbH
\**************************************************************************************************/

#ifndef ECUM_CBK_H
#define ECUM_CBK_H

/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/
#include "Std_Types.h"
#include "EcuM_Cfg.h"
#include "EcuM_Callout.h"
#include "Os.h"

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/

#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */ 

/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_CB_NfyNvMJobEnd
 *** 
 *** DESCRIPTION:
 ***     Used to notify about the end of NVRAM jobs initiated by EcuM The callback must be
 ***     callable from normal and interrupt execution contexts.
 ***     
 ***     ServiceID  : 0x65
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	uint8 ServiceId Unique Service ID of NVRAM manager service.
 ***	uint8 JobResult Covers the job result of the previous processed multi block job. 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
extern void EcuM_CB_NfyNvMJobEnd(uint8 ServiceId, uint8 JobResult);

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_SetWakeupEvent
 *** 
 *** DESCRIPTION:
 ***     Sets the wakeup event.
 ***     
 ***     ServiceID  : 0x0c
 ***     Reentrant  : false
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType sources Value to be set 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
extern void EcuM_SetWakeupEvent(EcuM_WakeupSourceType sources);

/**************************************************************************************************\
 *** FUNCTION:
 ***     EcuM_ValidateWakeupEvent
 *** 
 *** DESCRIPTION:
 ***     After wakeup, the ECU State Manager will stop the process during the WAKEUP
 ***     VALIDATION state/sequence to wait for validation of the wakeup event.This
 ***     API service is used to indicate to the ECU Manager module that the wakeup
 ***     events indicated in the sources parameter have been validated.
 ***     
 ***     ServiceID  : 0x14
 ***     Reentrant  : true
 ***
 *** PARAMETERS:
 ***    Type           Name   Description
 ***    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***	EcuM_WakeupSourceType sources Events that have been validated 
 *** 
 *** RETURNS:
 ***    void
\**************************************************************************************************/
extern void EcuM_ValidateWakeupEvent(EcuM_WakeupSourceType sources);



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 

#endif /* ECUM_CBK_H */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
