/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcucValueCollection
 *** Codefile            : Rte.c
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2025-06-11 08:50:23
 ***
 *** SystemDesk version  : 5.6.0.13023
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/

#ifndef RTE_C
#define RTE_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
#include "SchM_EcuM.h"
#include "Rte_SensorSWC.h"
#include "Rte_CruiseControl.h"
#include "Rte_ActuatorSWC.h"
#include "Rte_Main.h"
#include "Rte_EcuM.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/


/******************************************************************************\
   VAR_NOINIT_8BIT: global or static variables (RAM) | Width: 8
\******************************************************************************/
uint8 Rte_Signal_1;
uint8 Rte_Buffer_0;
uint8 Rte_Signal_8;

/******************************************************************************\
   VAR_NOINIT_BOOLEAN: global or static variables (RAM) | Width: 8
\******************************************************************************/
boolean Rte_Signal_2;
boolean Rte_Buffer_1;
boolean Rte_Signal_3;
boolean Rte_Buffer_2;
boolean Rte_Signal_5;
boolean Rte_Signal_6;
boolean Rte_Signal_7;
boolean Rte_Signal_9;
boolean Rte_Buffer_8;
boolean Rte_Buffer_9;
boolean Rte_Signal_11;

/******************************************************************************\
   VAR_NOINIT_32BIT: global or static variables (RAM) | Width: 32
\******************************************************************************/
float32 Rte_Signal_4;
float32 Rte_Buffer_3;
float32 Rte_Signal_10;
float32 Rte_Buffer_10;
float32 Rte_Buffer_11;
float32 Rte_Signal_12;
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/*************************************************************************************************\
 ***  TASK:
 ***      MainFunctionTask3_1ms
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      
 ***
 ***  SETTINGS:
 ***      Type:     BASIC
 ***      Priority: 15
 ***      Schedule: FULL
 ***
\*************************************************************************************************/
TASK(MainFunctionTask3_1ms) 
{

   /* Starts a runnable. */
   EcuM_MainFunction();

   /* Terminates a calling task. */
   TerminateTask();
}

/*************************************************************************************************\
 ***  TASK:
 ***      Task0_10ms
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      
 ***
 ***  SETTINGS:
 ***      Type:     BASIC
 ***      Priority: 10
 ***      Schedule: FULL
 ***
\*************************************************************************************************/
TASK(Task0_10ms) 
{

   /* Creates a copy of a signal or interrunnable variable. */
   Rte_Buffer_1 = Rte_Signal_2;

   /* Creates a copy of a signal or interrunnable variable. */
   Rte_Buffer_2 = Rte_Signal_3;

   /* Creates a copy of a signal or interrunnable variable. */
   Rte_Buffer_3 = Rte_Signal_4;

   /* Creates a copy of a signal or interrunnable variable. */
   Rte_Buffer_0 = Rte_Signal_1;

   /* Starts a runnable. */
   SensorSWC_ReadFromSim();

   /* Starts a runnable. */
   CruiseControl_AdjustSpeed();

   /* Writes a signal or interrunnable variable. */
   Rte_Signal_2 = RTE_IP_WRITE(RTE_IP_1, boolean, Rte_Buffer_1);

   /* Writes a signal or interrunnable variable. */
   Rte_Signal_3 = RTE_IP_WRITE(RTE_IP_2, boolean, Rte_Buffer_2);

   /* Writes a signal or interrunnable variable. */
   Rte_Signal_4 = RTE_IP_WRITE(RTE_IP_3, float32, Rte_Buffer_3);

   /* Writes a signal or interrunnable variable. */
   Rte_Signal_1 = RTE_IP_WRITE(RTE_IP_0, uint8, Rte_Buffer_0);

   /* Activates a runnable. */
   SetEvent(Task1, Rte_OsEvent_0);

   /* Terminates a calling task. */
   TerminateTask();
}

/*************************************************************************************************\
 ***  TASK:
 ***      Task1
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      
 ***
 ***  SETTINGS:
 ***      Type:     EXTENDED
 ***      Priority: 10
 ***      Schedule: FULL
 ***
\*************************************************************************************************/
TASK(Task1) 
{
   while (1)    {

      /* Related RTE event(s): */

      /* ReceivedCounter, ReceivedCC_StateNew, ReceivedAccelerate, ReceivedBrake, TargetSpeedReceive
      d, EmergencyBrakeReceived */
      WaitEvent(Rte_OsEvent_0);
      ClearEvent(Rte_OsEvent_0);

      /* Creates a copy of a signal or interrunnable variable. */
      Rte_Buffer_8 = Rte_Signal_9;

      /* Creates a copy of a signal or interrunnable variable. */
      Rte_Buffer_10 = Rte_Signal_10;

      /* Creates a copy of a signal or interrunnable variable. */
      Rte_Buffer_9 = RTE_IP_READ(RTE_IP_8, boolean, Rte_Buffer_8);

      /* Creates a copy of a signal or interrunnable variable. */
      Rte_Buffer_11 = RTE_IP_READ(RTE_IP_9, float32, Rte_Buffer_10);

      /* Starts a runnable. */
      ActuatorSWC_WriteToSim();
   }

   /* Terminates a calling task. */
   TerminateTask();
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_Start
 ***
 ***  DESCRIPTION:
 ***      Rte_Start is for allocating and initializing system resources and communication resources 
 ***      used by the RTE.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      Std_ReturnType
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
Std_ReturnType Rte_Start(void)
{
   Rte_Signal_1 = Rte_SigInitValue_Signal_1;
   Rte_Signal_2 = Rte_SigInitValue_Signal_2;
   Rte_Signal_3 = Rte_SigInitValue_Signal_3;
   Rte_Signal_4 = Rte_SigInitValue_Signal_4;
   Rte_Signal_5 = Rte_SigInitValue_Signal_5;
   Rte_Signal_6 = Rte_SigInitValue_Signal_6;
   Rte_Signal_7 = Rte_SigInitValue_Signal_7;
   Rte_Signal_8 = Rte_SigInitValue_Signal_8;
   Rte_Signal_9 = Rte_SigInitValue_Signal_9;
   Rte_Signal_10 = Rte_SigInitValue_Signal_10;
   Rte_Signal_11 = Rte_SigInitValue_Signal_11;
   Rte_Signal_12 = Rte_SigInitValue_Signal_12;

   /* Activate extended tasks without autostart. */
   ActivateTask(Task1);

   /* Start alarms and schedule tables for cyclic tasks. */
   SetRelAlarm(Rte_OsAlarm_Cyclic_Task0_10ms, (TickType) 1, (TickType) 10);

   /* API call return. */
   return RTE_E_OK;
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_Stop
 ***
 ***  DESCRIPTION:
 ***      Rte_Stop is used to finalize the RTE itself. This service releases all system and communic
 ***      ation resources allocated by the RTE.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      Std_ReturnType
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
Std_ReturnType Rte_Stop(void)
{

   /* Stop alarms and schedule tables for cyclic tasks. */
   CancelAlarm(Rte_OsAlarm_Cyclic_Task0_10ms);

   /* API call return. */
   return RTE_E_OK;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/


#endif/*RTE_C */
/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
