/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcucValueCollection
 *** Codefile            : Rte_CruiseControl.h
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2025-06-11 08:50:23
 ***
 *** SystemDesk version  : 5.6.0.13023
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/

#ifndef RTE_CRUISECONTROL_H
#define RTE_CRUISECONTROL_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
#include "Rte_CruiseControl_Type.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_CRUISECONTROL_C

/* Init value(s). */
#define Rte_InitValue_CC_State_Value 0 
#define Rte_InitValue_CurrentSpeed_Value 0.F 
#define Rte_InitValue_Accelerate_Value 0 
#define Rte_InitValue_Brake_Value 0 
#define Rte_InitValue_CC_StateNew_Value 0 
#endif 
#endif 
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_CRUISECONTROL_C

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_AdjustSpeed_CC_State_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_AdjustSpeed_CC_State_Value() \
(\
   Rte_Signal_11\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_AdjustSpeed_CurrentSpeed_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_AdjustSpeed_CurrentSpeed_Value() \
(\
   Rte_Signal_12\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWrite_AdjustSpeed_Accelerate_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an "implicit" write on a sender-receiver communication data with "data" semantics
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      boolean            Value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWrite_AdjustSpeed_Accelerate_Value(Value) \
(\
   Rte_Signal_5 = (Value)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWriteRef_AdjustSpeed_Accelerate_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit write on a sender-receiver communication data item with data semantic
 s.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      boolean *
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWriteRef_AdjustSpeed_Accelerate_Value() \
(\
   ((boolean *) &Rte_Signal_5)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWrite_AdjustSpeed_Brake_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an "implicit" write on a sender-receiver communication data with "data" semantics
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      boolean            Value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWrite_AdjustSpeed_Brake_Value(Value) \
(\
   Rte_Signal_6 = (Value)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWriteRef_AdjustSpeed_Brake_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit write on a sender-receiver communication data item with data semantic
 s.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      boolean *
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWriteRef_AdjustSpeed_Brake_Value() \
(\
   ((boolean *) &Rte_Signal_6)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWrite_AdjustSpeed_CC_StateNew_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an "implicit" write on a sender-receiver communication data with "data" semantics
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      boolean            Value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWrite_AdjustSpeed_CC_StateNew_Value(Value) \
(\
   Rte_Signal_7 = (Value)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWriteRef_AdjustSpeed_CC_StateNew_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit write on a sender-receiver communication data item with data semantic
 s.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      boolean *
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWriteRef_AdjustSpeed_CC_StateNew_Value() \
(\
   ((boolean *) &Rte_Signal_7)\
)

#endif 
#endif 
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/


/* runnables */
#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */ 

extern void CruiseControl_AdjustSpeed(void);
#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 


#endif/*RTE_CRUISECONTROL_H */
/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
