/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcucValueCollection
 *** Codefile            : Rte_ActuatorSWC.h
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2025-06-11 08:50:23
 ***
 *** SystemDesk version  : 5.6.0.13023
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/

#ifndef RTE_ACTUATORSWC_H
#define RTE_ACTUATORSWC_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
#include "Rte_ActuatorSWC_Type.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_ACTUATORSWC_C

/* Init value(s). */
#define Rte_InitValue_Accelerate_Value 0 
#define Rte_InitValue_Brake_Value 0 
#define Rte_InitValue_CC_StateNew_Value 0 
#define Rte_InitValue_Counter_Value 0 
#define Rte_InitValue_EmergencyBrake_Value 0 
#define Rte_InitValue_TargetSpeed_Value 0.F 
#endif 
#endif 
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_ACTUATORSWC_C

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_WriteToSim_Accelerate_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_WriteToSim_Accelerate_Value() \
(\
   Rte_Signal_5\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_WriteToSim_Brake_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_WriteToSim_Brake_Value() \
(\
   Rte_Signal_6\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_WriteToSim_CC_StateNew_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_WriteToSim_CC_StateNew_Value() \
(\
   Rte_Signal_7\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_WriteToSim_Counter_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      uint8
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_WriteToSim_Counter_Value() \
(\
   Rte_Signal_8\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_WriteToSim_EmergencyBrake_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_WriteToSim_EmergencyBrake_Value() \
(\
   Rte_Buffer_9\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_WriteToSim_TargetSpeed_Value
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_WriteToSim_TargetSpeed_Value() \
(\
   Rte_Buffer_11\
)

#endif 
#endif 
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/


/* runnables */
#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */ 

extern void ActuatorSWC_WriteToSim(void);
#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 


#endif/*RTE_ACTUATORSWC_H */
/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
