/**************************************************************************************************\
 *** 
 *** System              : System
 *** ECU                 : EcuInstance
 *** Configuration       : EcucValueCollection
 *** Codefile            : RteIv.c
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2025-06-11 08:50:23
 ***
 *** SystemDesk version  : 5.6.0.13023
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/

#ifndef RTEIV_C
#define RTEIV_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "RteIv.h"
#include "Dap.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/


/******************************************************************************\
   CONST_UNSPECIFIED: global or static constants (ROM) | Width: N.A.
\******************************************************************************/
const Rte_IvServiceType Rte_IvServices[6] = 
{
   /*[0..5]*/ Rte_IvsEcuFlatViewPrototype_SensorSWC_TargetSpeedButtonState_OutputService,
    Rte_IvsEcuFlatViewPrototype_SensorSWC_AcceleratorPedal_OutputService,
    Rte_IvsEcuFlatViewPrototype_SensorSWC_BrakePedal_OutputService,
    Rte_IvsEcuFlatViewPrototype_SensorSWC_DistanceLeading_OutputService,
    Rte_IvsActuatorSWC_TargetSpeed_InputService, Rte_IvsActuatorSWC_EmergencyBrake_InputService
   /* , , , , ,  */
};

/******************************************************************************\
   VAR_UNSPECIFIED: global or static variables (RAM) | Width: N.A.
\******************************************************************************/
Rte_IvServiceType Rte_IvCallback = 0;
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/


/* static functions */
#ifdef DAP_USE_SYNCHRONOUS_CALLBACK
static void Rte_DapSynchronousCallback(void * arg);
#endif 
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IvsEcuFlatViewPrototype_SensorSWC_TargetSpeedButtonState_OutputService
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      void *             value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
void Rte_IvsEcuFlatViewPrototype_SensorSWC_TargetSpeedButtonState_OutputService(uint32 id, void *
  value)
{
   uint8 Rte_AuxVar;
   uint8 Rte_AuxVar_1;
   (void) id;

   /* Entry dap group. */
   Dap_Entry_EcuFlatViewPrototype_SensorSWC_TargetSpeedButtonState_OutputService();

   /* Sets the intervention value. */
   Rte_AuxVar = *((uint8 *) value);
   Rte_AuxVar_1 = Rte_AuxVar;

   /* Writes a dap signal. */
   Dap_Write_Pp_EcuFlatViewPrototype_SensorSWC_TargetSpeedButtonState_OutputService_output(&Rte_AuxVar_1);

   /* Exits a dap group. */
   Dap_Exit_EcuFlatViewPrototype_SensorSWC_TargetSpeedButtonState_OutputService();
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IvsEcuFlatViewPrototype_SensorSWC_AcceleratorPedal_OutputService
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      void *             value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
void Rte_IvsEcuFlatViewPrototype_SensorSWC_AcceleratorPedal_OutputService(uint32 id, void * value)
{
   boolean Rte_AuxVar;
   boolean Rte_AuxVar_1;
   (void) id;

   /* Entry dap group. */
   Dap_Entry_EcuFlatViewPrototype_SensorSWC_AcceleratorPedal_OutputService();

   /* Sets the intervention value. */
   Rte_AuxVar = *((boolean *) value);
   Rte_AuxVar_1 = Rte_AuxVar;

   /* Writes a dap signal. */
   Dap_Write_Pp_EcuFlatViewPrototype_SensorSWC_AcceleratorPedal_OutputService_output(&Rte_AuxVar_1);

   /* Exits a dap group. */
   Dap_Exit_EcuFlatViewPrototype_SensorSWC_AcceleratorPedal_OutputService();
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IvsEcuFlatViewPrototype_SensorSWC_BrakePedal_OutputService
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      void *             value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
void Rte_IvsEcuFlatViewPrototype_SensorSWC_BrakePedal_OutputService(uint32 id, void * value)
{
   boolean Rte_AuxVar;
   boolean Rte_AuxVar_1;
   (void) id;

   /* Entry dap group. */
   Dap_Entry_EcuFlatViewPrototype_SensorSWC_BrakePedal_OutputService();

   /* Sets the intervention value. */
   Rte_AuxVar = *((boolean *) value);
   Rte_AuxVar_1 = Rte_AuxVar;

   /* Writes a dap signal. */
   Dap_Write_Pp_EcuFlatViewPrototype_SensorSWC_BrakePedal_OutputService_output(&Rte_AuxVar_1);

   /* Exits a dap group. */
   Dap_Exit_EcuFlatViewPrototype_SensorSWC_BrakePedal_OutputService();
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IvsEcuFlatViewPrototype_SensorSWC_DistanceLeading_OutputService
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      void *             value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
void Rte_IvsEcuFlatViewPrototype_SensorSWC_DistanceLeading_OutputService(uint32 id, void * value)
{
   float32 Rte_AuxVar;
   float32 Rte_AuxVar_1;
   (void) id;

   /* Entry dap group. */
   Dap_Entry_EcuFlatViewPrototype_SensorSWC_DistanceLeading_OutputService();

   /* Sets the intervention value. */
   Rte_AuxVar = *((float32 *) value);
   Rte_AuxVar_1 = Rte_AuxVar;

   /* Writes a dap signal. */
   Dap_Write_Pp_EcuFlatViewPrototype_SensorSWC_DistanceLeading_OutputService_output(&Rte_AuxVar_1);

   /* Exits a dap group. */
   Dap_Exit_EcuFlatViewPrototype_SensorSWC_DistanceLeading_OutputService();
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IvsActuatorSWC_TargetSpeed_InputService
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      void *             value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
void Rte_IvsActuatorSWC_TargetSpeed_InputService(uint32 id, void * value)
{
   float32 Rte_AuxVar;
   float32 Rte_AuxVar_1;
   (void) id;

   /* Entry dap group. */
   Dap_Entry_ActuatorSWC_TargetSpeed_InputService();

   /* Reads a dap signal. */
   Dap_Read_Rp_ActuatorSWC_TargetSpeed_InputService_input(&Rte_AuxVar);
   Rte_AuxVar_1 = Rte_AuxVar;

   /* Exits a dap group. */
   Dap_Exit_ActuatorSWC_TargetSpeed_InputService();

   /* Sets the intervention value. */
   *((float32 *) value) = Rte_AuxVar_1;
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IvsActuatorSWC_EmergencyBrake_InputService
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      void *             value               
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
void Rte_IvsActuatorSWC_EmergencyBrake_InputService(uint32 id, void * value)
{
   boolean Rte_AuxVar;
   boolean Rte_AuxVar_1;
   (void) id;

   /* Entry dap group. */
   Dap_Entry_ActuatorSWC_EmergencyBrake_InputService();

   /* Reads a dap signal. */
   Dap_Read_Rp_ActuatorSWC_EmergencyBrake_InputService_input(&Rte_AuxVar);
   Rte_AuxVar_1 = Rte_AuxVar;

   /* Exits a dap group. */
   Dap_Exit_ActuatorSWC_EmergencyBrake_InputService();

   /* Sets the intervention value. */
   *((boolean *) value) = Rte_AuxVar_1;
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IpReadWrite_uint8
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      uint8              value               
 ***
 ***  RETURNS:
 ***      uint8
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
uint8 Rte_IpReadWrite_uint8(uint32 id, uint8 value)
{
   if (TRUE == RTE_IP_SERVICE_AVAILABLE(id)) {
      #ifdef DAP_USE_SYNCHRONOUS_CALLBACK
      if (RTE_IP_CALL_BY_CALLBACK(id)) {
         Rte_IvServiceCallType Rte_AuxVar;
         Rte_AuxVar.id = id;
         Rte_AuxVar.value = (void *) &value;
         Rte_AuxVar.service = Rte_IvServices[RTE_IP_SERVICE_INDEX(id)];
         Dap_InvokeSynchronousCallback(Rte_DapSynchronousCallback, (void *) &Rte_AuxVar);
      }
      else {
         Rte_IvServices[RTE_IP_SERVICE_INDEX(id)](id,((void *) &value));
      }
      #else 
      Rte_IvServices[RTE_IP_SERVICE_INDEX(id)](id,((void *) &value));
      #endif 
   }
   else {
      if (TRUE == RTE_IP_CALLBACK_REGISTERED) {
         Rte_IvCallback(id, (void *) &value);
      }
   }
   return value;
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IpReadWrite_boolean
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      boolean            value               
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
boolean Rte_IpReadWrite_boolean(uint32 id, boolean value)
{
   if (TRUE == RTE_IP_SERVICE_AVAILABLE(id)) {
      #ifdef DAP_USE_SYNCHRONOUS_CALLBACK
      if (RTE_IP_CALL_BY_CALLBACK(id)) {
         Rte_IvServiceCallType Rte_AuxVar;
         Rte_AuxVar.id = id;
         Rte_AuxVar.value = (void *) &value;
         Rte_AuxVar.service = Rte_IvServices[RTE_IP_SERVICE_INDEX(id)];
         Dap_InvokeSynchronousCallback(Rte_DapSynchronousCallback, (void *) &Rte_AuxVar);
      }
      else {
         Rte_IvServices[RTE_IP_SERVICE_INDEX(id)](id,((void *) &value));
      }
      #else 
      Rte_IvServices[RTE_IP_SERVICE_INDEX(id)](id,((void *) &value));
      #endif 
   }
   else {
      if (TRUE == RTE_IP_CALLBACK_REGISTERED) {
         Rte_IvCallback(id, (void *) &value);
      }
   }
   return value;
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_IpReadWrite_float32
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      uint32             id                  
 ***      float32            value               
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
float32 Rte_IpReadWrite_float32(uint32 id, float32 value)
{
   if (TRUE == RTE_IP_SERVICE_AVAILABLE(id)) {
      #ifdef DAP_USE_SYNCHRONOUS_CALLBACK
      if (RTE_IP_CALL_BY_CALLBACK(id)) {
         Rte_IvServiceCallType Rte_AuxVar;
         Rte_AuxVar.id = id;
         Rte_AuxVar.value = (void *) &value;
         Rte_AuxVar.service = Rte_IvServices[RTE_IP_SERVICE_INDEX(id)];
         Dap_InvokeSynchronousCallback(Rte_DapSynchronousCallback, (void *) &Rte_AuxVar);
      }
      else {
         Rte_IvServices[RTE_IP_SERVICE_INDEX(id)](id,((void *) &value));
      }
      #else 
      Rte_IvServices[RTE_IP_SERVICE_INDEX(id)](id,((void *) &value));
      #endif 
   }
   else {
      if (TRUE == RTE_IP_CALLBACK_REGISTERED) {
         Rte_IvCallback(id, (void *) &value);
      }
   }
   return value;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

#ifdef DAP_USE_SYNCHRONOUS_CALLBACK
/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_DapSynchronousCallback
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      void *             arg                 
 ***
 ***  RETURNS:
 ***      static void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
static void Rte_DapSynchronousCallback(void * arg)
{
   Rte_IvServiceCallType * Rte_AuxVar = (Rte_IvServiceCallType *) arg;
   Rte_AuxVar->service(Rte_AuxVar->id, Rte_AuxVar->value);
}

#endif 

#endif/*RTEIV_C */
/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
